package Modulos;

import java.applet.AudioClip;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author leonardo
 */
public class Banio2 extends javax.swing.JFrame {

    /**
     * Creates new form Banio2
     */
    public Banio2() {
        initComponents();
        this.setSize(559,610);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        l19.setVisible(false);
        l16.setVisible(false);
        l15.setVisible(false);
        l17.setVisible(false);
        l18.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        l19 = new javax.swing.JLabel();
        l16 = new javax.swing.JLabel();
        l15 = new javax.swing.JLabel();
        l17 = new javax.swing.JLabel();
        l18 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton34.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jButton34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/40.png"))); // NOI18N
        jButton34.setText("16");
        jButton34.setBorder(null);
        jButton34.setBorderPainted(false);
        jButton34.setContentAreaFilled(false);
        jButton34.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton34.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton34.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/25.png"))); // NOI18N
        jButton34.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/35.png"))); // NOI18N
        jButton34.setVerifyInputWhenFocusTarget(false);
        jButton34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton34ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton34);
        jButton34.setBounds(290, 200, 40, 40);

        jButton35.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jButton35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/40.png"))); // NOI18N
        jButton35.setText("15");
        jButton35.setBorder(null);
        jButton35.setBorderPainted(false);
        jButton35.setContentAreaFilled(false);
        jButton35.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton35.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton35.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/25.png"))); // NOI18N
        jButton35.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/35.png"))); // NOI18N
        jButton35.setVerifyInputWhenFocusTarget(false);
        jButton35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton35ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton35);
        jButton35.setBounds(200, 70, 40, 40);

        jButton31.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jButton31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/40.png"))); // NOI18N
        jButton31.setText("17");
        jButton31.setBorder(null);
        jButton31.setBorderPainted(false);
        jButton31.setContentAreaFilled(false);
        jButton31.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton31.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton31.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/25.png"))); // NOI18N
        jButton31.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/35.png"))); // NOI18N
        jButton31.setVerifyInputWhenFocusTarget(false);
        jButton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton31ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton31);
        jButton31.setBounds(300, 360, 40, 40);

        jButton32.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jButton32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/40.png"))); // NOI18N
        jButton32.setText("19");
        jButton32.setBorder(null);
        jButton32.setBorderPainted(false);
        jButton32.setContentAreaFilled(false);
        jButton32.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton32.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton32.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/25.png"))); // NOI18N
        jButton32.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/35.png"))); // NOI18N
        jButton32.setVerifyInputWhenFocusTarget(false);
        jButton32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton32ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton32);
        jButton32.setBounds(70, 220, 40, 40);

        jButton33.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jButton33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/40.png"))); // NOI18N
        jButton33.setText("18");
        jButton33.setBorder(null);
        jButton33.setBorderPainted(false);
        jButton33.setContentAreaFilled(false);
        jButton33.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton33.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton33.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/25.png"))); // NOI18N
        jButton33.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/35.png"))); // NOI18N
        jButton33.setVerifyInputWhenFocusTarget(false);
        jButton33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton33ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton33);
        jButton33.setBounds(480, 260, 40, 40);

        l19.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        l19.setText("toilet paper");
        l19.setOpaque(true);
        getContentPane().add(l19);
        l19.setBounds(30, 190, 130, 30);

        l16.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        l16.setText("top");
        l16.setOpaque(true);
        getContentPane().add(l16);
        l16.setBounds(280, 170, 40, 30);

        l15.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        l15.setText("box");
        l15.setOpaque(true);
        getContentPane().add(l15);
        l15.setBounds(190, 50, 70, 30);

        l17.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        l17.setText("toilet");
        l17.setOpaque(true);
        getContentPane().add(l17);
        l17.setBounds(290, 410, 70, 30);

        l18.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        l18.setText("plunger");
        l18.setOpaque(true);
        getContentPane().add(l18);
        l18.setBounds(450, 230, 90, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 502, 100, 80);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondos/fbanio3.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 560, 580);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton31ActionPerformed
 AudioClip sonido;
        sonido= java.applet.Applet.newAudioClip(getClass().getResource("/audio/toilet.wav"));
        sonido.play();        // TODO add your handling code here:
        l19.setVisible(false);
        l16.setVisible(false);
        l15.setVisible(false);
        l17.setVisible(true);
        l18.setVisible(false);
        
    }//GEN-LAST:event_jButton31ActionPerformed

    private void jButton32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton32ActionPerformed
         AudioClip sonido;
        sonido= java.applet.Applet.newAudioClip(getClass().getResource("/audio/toilet paper.wav"));
        sonido.play();// TODO add your handling code here:
        l19.setVisible(true);
        l16.setVisible(false);
        l15.setVisible(false);
        l17.setVisible(false);
        l18.setVisible(false);
        
    }//GEN-LAST:event_jButton32ActionPerformed

    private void jButton33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton33ActionPerformed
      AudioClip sonido;
        sonido= java.applet.Applet.newAudioClip(getClass().getResource("/audio/plunger.wav"));
        sonido.play();   // TODO add your handling code here:
        l19.setVisible(false);
        l16.setVisible(false);
        l15.setVisible(false);
        l17.setVisible(false);
        l18.setVisible(true);
        
    }//GEN-LAST:event_jButton33ActionPerformed

    private void jButton34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton34ActionPerformed
 AudioClip sonido;
        sonido= java.applet.Applet.newAudioClip(getClass().getResource("/audio/top.wav"));
        sonido.play();        // TODO add your handling code here:
        l19.setVisible(false);
        l16.setVisible(true);
        l15.setVisible(false);
        l17.setVisible(false);
        l18.setVisible(false);
        
    }//GEN-LAST:event_jButton34ActionPerformed

    private void jButton35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton35ActionPerformed
 AudioClip sonido;
        sonido= java.applet.Applet.newAudioClip(getClass().getResource("/audio/box.wav"));
        sonido.play();        // TODO add your handling code here:
        l19.setVisible(false);
        l16.setVisible(false);
        l15.setVisible(true);
        l17.setVisible(false);
        l18.setVisible(false);
        
    }//GEN-LAST:event_jButton35ActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        this.dispose();
        new Banio().setVisible(true);
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Banio2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Banio2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Banio2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Banio2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Banio2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel l15;
    private javax.swing.JLabel l16;
    private javax.swing.JLabel l17;
    private javax.swing.JLabel l18;
    private javax.swing.JLabel l19;
    // End of variables declaration//GEN-END:variables
}
