package Modulos;

import java.applet.AudioClip;

public class ComidaRapida extends javax.swing.JFrame {
    public ComidaRapida() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setSize(970,690);
        l1.setVisible(false);
        l2.setVisible(false);
        l3.setVisible(false);
        l4.setVisible(false);
        l5.setVisible(false);
        l6.setVisible(false);
        l7.setVisible(false);
        l8.setVisible(false);
        l9.setVisible(false);
        l10.setVisible(false);
        l11.setVisible(false);
        l12.setVisible(false);
        l13.setVisible(false);
        l14.setVisible(false);
        l15.setVisible(false);
        l16.setVisible(false);
        l17.setVisible(false);
        l18.setVisible(false);
        l19.setVisible(false);
        l20.setVisible(false);
        l21.setVisible(false);
        l22.setVisible(false);
        l23.setVisible(false);
        l24.setVisible(false);
        l25.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        b9 = new javax.swing.JButton();
        b10 = new javax.swing.JButton();
        b11 = new javax.swing.JButton();
        b12 = new javax.swing.JButton();
        b13 = new javax.swing.JButton();
        b14 = new javax.swing.JButton();
        b15 = new javax.swing.JButton();
        b16 = new javax.swing.JButton();
        b17 = new javax.swing.JButton();
        b18 = new javax.swing.JButton();
        b19 = new javax.swing.JButton();
        b20 = new javax.swing.JButton();
        b21 = new javax.swing.JButton();
        b22 = new javax.swing.JButton();
        b23 = new javax.swing.JButton();
        b24 = new javax.swing.JButton();
        b25 = new javax.swing.JButton();
        jSalir = new javax.swing.JButton();
        l1 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        l4 = new javax.swing.JLabel();
        l5 = new javax.swing.JLabel();
        l6 = new javax.swing.JLabel();
        l7 = new javax.swing.JLabel();
        l8 = new javax.swing.JLabel();
        l9 = new javax.swing.JLabel();
        l10 = new javax.swing.JLabel();
        l11 = new javax.swing.JLabel();
        l12 = new javax.swing.JLabel();
        l13 = new javax.swing.JLabel();
        l14 = new javax.swing.JLabel();
        l15 = new javax.swing.JLabel();
        l16 = new javax.swing.JLabel();
        l17 = new javax.swing.JLabel();
        l18 = new javax.swing.JLabel();
        l19 = new javax.swing.JLabel();
        l20 = new javax.swing.JLabel();
        l21 = new javax.swing.JLabel();
        l22 = new javax.swing.JLabel();
        l23 = new javax.swing.JLabel();
        l24 = new javax.swing.JLabel();
        l25 = new javax.swing.JLabel();
        jFondo = new javax.swing.JLabel();
        l26 = new javax.swing.JLabel();
        l27 = new javax.swing.JLabel();
        l28 = new javax.swing.JLabel();
        l29 = new javax.swing.JLabel();
        l31 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        b1.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        b1.setForeground(new java.awt.Color(240, 240, 240));
        b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/45.png"))); // NOI18N
        b1.setText("1");
        b1.setBorderPainted(false);
        b1.setContentAreaFilled(false);
        b1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        b1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/35.png"))); // NOI18N
        b1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/40.png"))); // NOI18N
        b1.setVerifyInputWhenFocusTarget(false);
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        getContentPane().add(b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 50, 50));

        b2.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        b2.setForeground(new java.awt.Color(240, 240, 240));
        b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/45.png"))); // NOI18N
        b2.setText("2");
        b2.setBorderPainted(false);
        b2.setContentAreaFilled(false);
        b2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        b2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/35.png"))); // NOI18N
        b2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/40.png"))); // NOI18N
        b2.setVerifyInputWhenFocusTarget(false);
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        getContentPane().add(b2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 50, 50));

        b3.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        b3.setForeground(new java.awt.Color(240, 240, 240));
        b3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/45.png"))); // NOI18N
        b3.setText("3");
        b3.setBorderPainted(false);
        b3.setContentAreaFilled(false);
        b3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        b3.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/35.png"))); // NOI18N
        b3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/40.png"))); // NOI18N
        b3.setVerifyInputWhenFocusTarget(false);
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        getContentPane().add(b3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 620, 50, 50));

        b4.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        b4.setForeground(new java.awt.Color(240, 240, 240));
        b4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/45.png"))); // NOI18N
        b4.setText("4");
        b4.setBorderPainted(false);
        b4.setContentAreaFilled(false);
        b4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        b4.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/35.png"))); // NOI18N
        b4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/40.png"))); // NOI18N
        b4.setVerifyInputWhenFocusTarget(false);
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });
        getContentPane().add(b4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, 50, 50));

        b5.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        b5.setForeground(new java.awt.Color(240, 240, 240));
        b5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/45.png"))); // NOI18N
        b5.setText("5");
        b5.setBorderPainted(false);
        b5.setContentAreaFilled(false);
        b5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        b5.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/35.png"))); // NOI18N
        b5.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/40.png"))); // NOI18N
        b5.setVerifyInputWhenFocusTarget(false);
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });
        getContentPane().add(b5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 500, 50, 50));

        b6.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        b6.setForeground(new java.awt.Color(240, 240, 240));
        b6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/45.png"))); // NOI18N
        b6.setText("6");
        b6.setBorderPainted(false);
        b6.setContentAreaFilled(false);
        b6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        b6.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/35.png"))); // NOI18N
        b6.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/40.png"))); // NOI18N
        b6.setVerifyInputWhenFocusTarget(false);
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });
        getContentPane().add(b6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 580, 50, 50));

        b7.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        b7.setForeground(new java.awt.Color(240, 240, 240));
        b7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/45.png"))); // NOI18N
        b7.setText("7");
        b7.setBorderPainted(false);
        b7.setContentAreaFilled(false);
        b7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        b7.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/35.png"))); // NOI18N
        b7.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/40.png"))); // NOI18N
        b7.setVerifyInputWhenFocusTarget(false);
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });
        getContentPane().add(b7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 50, 50));

        b8.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        b8.setForeground(new java.awt.Color(240, 240, 240));
        b8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/45.png"))); // NOI18N
        b8.setText("8");
        b8.setBorderPainted(false);
        b8.setContentAreaFilled(false);
        b8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        b8.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/35.png"))); // NOI18N
        b8.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/40.png"))); // NOI18N
        b8.setVerifyInputWhenFocusTarget(false);
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });
        getContentPane().add(b8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 400, 50, 50));

        b9.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        b9.setForeground(new java.awt.Color(240, 240, 240));
        b9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/45.png"))); // NOI18N
        b9.setText("9");
        b9.setBorderPainted(false);
        b9.setContentAreaFilled(false);
        b9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        b9.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/35.png"))); // NOI18N
        b9.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/40.png"))); // NOI18N
        b9.setVerifyInputWhenFocusTarget(false);
        b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b9ActionPerformed(evt);
            }
        });
        getContentPane().add(b9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 50, 50));

        b10.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        b10.setForeground(new java.awt.Color(240, 240, 240));
        b10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/45.png"))); // NOI18N
        b10.setText("10");
        b10.setBorderPainted(false);
        b10.setContentAreaFilled(false);
        b10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        b10.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/35.png"))); // NOI18N
        b10.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/40.png"))); // NOI18N
        b10.setVerifyInputWhenFocusTarget(false);
        b10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b10ActionPerformed(evt);
            }
        });
        getContentPane().add(b10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 70, 50));

        b11.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        b11.setForeground(new java.awt.Color(240, 240, 240));
        b11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/45.png"))); // NOI18N
        b11.setText("11");
        b11.setBorderPainted(false);
        b11.setContentAreaFilled(false);
        b11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        b11.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/35.png"))); // NOI18N
        b11.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/40.png"))); // NOI18N
        b11.setVerifyInputWhenFocusTarget(false);
        b11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b11ActionPerformed(evt);
            }
        });
        getContentPane().add(b11, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 200, 60, 50));

        b12.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        b12.setForeground(new java.awt.Color(240, 240, 240));
        b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/45.png"))); // NOI18N
        b12.setText("12");
        b12.setBorderPainted(false);
        b12.setContentAreaFilled(false);
        b12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        b12.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/35.png"))); // NOI18N
        b12.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/40.png"))); // NOI18N
        b12.setVerifyInputWhenFocusTarget(false);
        b12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b12ActionPerformed(evt);
            }
        });
        getContentPane().add(b12, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 340, 60, 60));

        b13.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        b13.setForeground(new java.awt.Color(240, 240, 240));
        b13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/45.png"))); // NOI18N
        b13.setText("13");
        b13.setBorderPainted(false);
        b13.setContentAreaFilled(false);
        b13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        b13.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/35.png"))); // NOI18N
        b13.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/40.png"))); // NOI18N
        b13.setVerifyInputWhenFocusTarget(false);
        b13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b13ActionPerformed(evt);
            }
        });
        getContentPane().add(b13, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 590, 60, 50));

        b14.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        b14.setForeground(new java.awt.Color(240, 240, 240));
        b14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/45.png"))); // NOI18N
        b14.setText("14");
        b14.setBorderPainted(false);
        b14.setContentAreaFilled(false);
        b14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        b14.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/35.png"))); // NOI18N
        b14.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/40.png"))); // NOI18N
        b14.setVerifyInputWhenFocusTarget(false);
        b14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b14ActionPerformed(evt);
            }
        });
        getContentPane().add(b14, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 60, 60));

        b15.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        b15.setForeground(new java.awt.Color(240, 240, 240));
        b15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/45.png"))); // NOI18N
        b15.setText("15");
        b15.setBorderPainted(false);
        b15.setContentAreaFilled(false);
        b15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        b15.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/35.png"))); // NOI18N
        b15.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/40.png"))); // NOI18N
        b15.setVerifyInputWhenFocusTarget(false);
        b15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b15ActionPerformed(evt);
            }
        });
        getContentPane().add(b15, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 550, 60, 60));

        b16.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        b16.setForeground(new java.awt.Color(240, 240, 240));
        b16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/45.png"))); // NOI18N
        b16.setText("16");
        b16.setBorderPainted(false);
        b16.setContentAreaFilled(false);
        b16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b16.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        b16.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/35.png"))); // NOI18N
        b16.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/40.png"))); // NOI18N
        b16.setVerifyInputWhenFocusTarget(false);
        b16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b16ActionPerformed(evt);
            }
        });
        getContentPane().add(b16, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 60, 50));

        b17.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        b17.setForeground(new java.awt.Color(240, 240, 240));
        b17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/45.png"))); // NOI18N
        b17.setText("17");
        b17.setBorderPainted(false);
        b17.setContentAreaFilled(false);
        b17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b17.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        b17.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/35.png"))); // NOI18N
        b17.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/40.png"))); // NOI18N
        b17.setVerifyInputWhenFocusTarget(false);
        b17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b17ActionPerformed(evt);
            }
        });
        getContentPane().add(b17, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 440, 60, 50));

        b18.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        b18.setForeground(new java.awt.Color(240, 240, 240));
        b18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/45.png"))); // NOI18N
        b18.setText("18");
        b18.setBorderPainted(false);
        b18.setContentAreaFilled(false);
        b18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b18.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        b18.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/35.png"))); // NOI18N
        b18.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/40.png"))); // NOI18N
        b18.setVerifyInputWhenFocusTarget(false);
        b18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b18ActionPerformed(evt);
            }
        });
        getContentPane().add(b18, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 470, 60, 60));

        b19.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        b19.setForeground(new java.awt.Color(240, 240, 240));
        b19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/45.png"))); // NOI18N
        b19.setText("19");
        b19.setBorderPainted(false);
        b19.setContentAreaFilled(false);
        b19.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b19.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        b19.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/35.png"))); // NOI18N
        b19.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/40.png"))); // NOI18N
        b19.setVerifyInputWhenFocusTarget(false);
        b19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b19ActionPerformed(evt);
            }
        });
        getContentPane().add(b19, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 560, 60, 60));

        b20.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        b20.setForeground(new java.awt.Color(240, 240, 240));
        b20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/45.png"))); // NOI18N
        b20.setText("20");
        b20.setBorderPainted(false);
        b20.setContentAreaFilled(false);
        b20.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b20.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        b20.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/35.png"))); // NOI18N
        b20.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/40.png"))); // NOI18N
        b20.setVerifyInputWhenFocusTarget(false);
        b20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b20ActionPerformed(evt);
            }
        });
        getContentPane().add(b20, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 410, 60, 50));

        b21.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        b21.setForeground(new java.awt.Color(240, 240, 240));
        b21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/45.png"))); // NOI18N
        b21.setText("21");
        b21.setBorderPainted(false);
        b21.setContentAreaFilled(false);
        b21.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b21.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        b21.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/35.png"))); // NOI18N
        b21.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/40.png"))); // NOI18N
        b21.setVerifyInputWhenFocusTarget(false);
        b21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b21ActionPerformed(evt);
            }
        });
        getContentPane().add(b21, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 170, 60, 50));

        b22.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        b22.setForeground(new java.awt.Color(240, 240, 240));
        b22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/45.png"))); // NOI18N
        b22.setText("22");
        b22.setBorderPainted(false);
        b22.setContentAreaFilled(false);
        b22.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b22.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        b22.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/35.png"))); // NOI18N
        b22.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/40.png"))); // NOI18N
        b22.setVerifyInputWhenFocusTarget(false);
        b22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b22ActionPerformed(evt);
            }
        });
        getContentPane().add(b22, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 220, 60, 60));

        b23.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        b23.setForeground(new java.awt.Color(240, 240, 240));
        b23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/45.png"))); // NOI18N
        b23.setText("23");
        b23.setBorderPainted(false);
        b23.setContentAreaFilled(false);
        b23.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b23.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        b23.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/35.png"))); // NOI18N
        b23.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/40.png"))); // NOI18N
        b23.setVerifyInputWhenFocusTarget(false);
        b23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b23ActionPerformed(evt);
            }
        });
        getContentPane().add(b23, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 590, 60, 50));

        b24.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        b24.setForeground(new java.awt.Color(240, 240, 240));
        b24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/45.png"))); // NOI18N
        b24.setText("24");
        b24.setBorderPainted(false);
        b24.setContentAreaFilled(false);
        b24.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b24.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        b24.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/35.png"))); // NOI18N
        b24.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/40.png"))); // NOI18N
        b24.setVerifyInputWhenFocusTarget(false);
        b24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b24ActionPerformed(evt);
            }
        });
        getContentPane().add(b24, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 390, 60, 50));

        b25.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        b25.setForeground(new java.awt.Color(240, 240, 240));
        b25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/45.png"))); // NOI18N
        b25.setText("25");
        b25.setBorderPainted(false);
        b25.setContentAreaFilled(false);
        b25.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b25.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        b25.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/35.png"))); // NOI18N
        b25.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/40.png"))); // NOI18N
        b25.setVerifyInputWhenFocusTarget(false);
        b25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b25ActionPerformed(evt);
            }
        });
        getContentPane().add(b25, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 490, 60, 50));

        jSalir.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jSalir.setForeground(new java.awt.Color(240, 240, 240));
        jSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/45.png"))); // NOI18N
        jSalir.setText("<");
        jSalir.setBorderPainted(false);
        jSalir.setContentAreaFilled(false);
        jSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jSalir.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/35.png"))); // NOI18N
        jSalir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/40.png"))); // NOI18N
        jSalir.setVerifyInputWhenFocusTarget(false);
        jSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 70));

        l1.setBackground(new java.awt.Color(204, 204, 204));
        l1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        l1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l1.setText("Soda Machine");
        l1.setOpaque(true);
        getContentPane().add(l1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 150, 30));

        l2.setBackground(new java.awt.Color(204, 204, 204));
        l2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        l2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l2.setText("Header");
        l2.setOpaque(true);
        getContentPane().add(l2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 110, 30));

        l3.setBackground(new java.awt.Color(204, 204, 204));
        l3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        l3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l3.setText("Plate");
        l3.setOpaque(true);
        getContentPane().add(l3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 620, 120, 30));

        l4.setBackground(new java.awt.Color(204, 204, 204));
        l4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        l4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l4.setText("Client");
        l4.setOpaque(true);
        getContentPane().add(l4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, 70, 30));

        l5.setBackground(new java.awt.Color(204, 204, 204));
        l5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        l5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l5.setText("Shoes");
        l5.setOpaque(true);
        getContentPane().add(l5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 540, 70, -1));

        l6.setBackground(new java.awt.Color(204, 204, 204));
        l6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        l6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l6.setText("Skewers");
        l6.setOpaque(true);
        getContentPane().add(l6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 620, 100, 30));

        l7.setBackground(new java.awt.Color(204, 204, 204));
        l7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        l7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l7.setText("Menu");
        l7.setOpaque(true);
        getContentPane().add(l7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 70, 30));

        l8.setBackground(new java.awt.Color(204, 204, 204));
        l8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        l8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l8.setText("Bar");
        l8.setOpaque(true);
        getContentPane().add(l8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 430, 110, 30));

        l9.setBackground(new java.awt.Color(204, 204, 204));
        l9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        l9.setText("Cap");
        l9.setOpaque(true);
        getContentPane().add(l9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 60, 30));

        l10.setBackground(new java.awt.Color(204, 204, 204));
        l10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        l10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l10.setText("Dish");
        l10.setOpaque(true);
        getContentPane().add(l10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, 70, 30));

        l11.setBackground(new java.awt.Color(204, 204, 204));
        l11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        l11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l11.setText("Cashier");
        l11.setOpaque(true);
        getContentPane().add(l11, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 220, 80, 30));

        l12.setBackground(new java.awt.Color(204, 204, 204));
        l12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        l12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l12.setText("Fried Chicken");
        l12.setOpaque(true);
        getContentPane().add(l12, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 350, 120, 30));

        l13.setBackground(new java.awt.Color(204, 204, 204));
        l13.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        l13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l13.setText("Beverage");
        l13.setOpaque(true);
        getContentPane().add(l13, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 600, 80, 30));

        l14.setBackground(new java.awt.Color(204, 204, 204));
        l14.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        l14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l14.setText("Dessert");
        l14.setOpaque(true);
        getContentPane().add(l14, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, 70, 30));

        l15.setBackground(new java.awt.Color(204, 204, 204));
        l15.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        l15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l15.setText("Table");
        l15.setOpaque(true);
        getContentPane().add(l15, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 560, 100, 30));

        l16.setBackground(new java.awt.Color(204, 204, 204));
        l16.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        l16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l16.setText("Nuggets");
        l16.setOpaque(true);
        getContentPane().add(l16, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 130, 30));

        l17.setBackground(new java.awt.Color(204, 204, 204));
        l17.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        l17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l17.setText("Salad");
        l17.setOpaque(true);
        getContentPane().add(l17, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 420, 70, 30));

        l18.setBackground(new java.awt.Color(204, 204, 204));
        l18.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        l18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l18.setText("Floor");
        l18.setOpaque(true);
        getContentPane().add(l18, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 480, 100, 30));

        l19.setBackground(new java.awt.Color(204, 204, 204));
        l19.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        l19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l19.setText("Bags");
        l19.setOpaque(true);
        getContentPane().add(l19, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 550, 90, 30));

        l20.setBackground(new java.awt.Color(204, 204, 204));
        l20.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        l20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l20.setText("French Fries");
        l20.setOpaque(true);
        getContentPane().add(l20, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 450, 120, 30));

        l21.setBackground(new java.awt.Color(204, 204, 204));
        l21.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        l21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l21.setText("Ad");
        l21.setOpaque(true);
        getContentPane().add(l21, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 180, 50, 30));

        l22.setBackground(new java.awt.Color(204, 204, 204));
        l22.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        l22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l22.setText("Computer");
        l22.setOpaque(true);
        getContentPane().add(l22, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 240, 90, -1));

        l23.setBackground(new java.awt.Color(204, 204, 204));
        l23.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        l23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l23.setText("Chair");
        l23.setOpaque(true);
        getContentPane().add(l23, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 600, 90, 30));

        l24.setBackground(new java.awt.Color(204, 204, 204));
        l24.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        l24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l24.setText("Burger");
        l24.setOpaque(true);
        getContentPane().add(l24, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 410, 90, 30));

        l25.setBackground(new java.awt.Color(204, 204, 204));
        l25.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        l25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l25.setText("Bowl");
        l25.setOpaque(true);
        getContentPane().add(l25, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 520, 90, 30));

        jFondo.setBackground(new java.awt.Color(153, 153, 153));
        jFondo.setForeground(new java.awt.Color(255, 255, 255));
        jFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondos/fcrapida.png"))); // NOI18N
        jFondo.setOpaque(true);
        getContentPane().add(jFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 670));

        l26.setBackground(new java.awt.Color(204, 204, 204));
        l26.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        l26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l26.setText("Soda Machine");
        l26.setOpaque(true);
        getContentPane().add(l26, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 150, 30));

        l27.setBackground(new java.awt.Color(204, 204, 204));
        l27.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        l27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l27.setText("Header");
        l27.setOpaque(true);
        getContentPane().add(l27, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 110, 30));

        l28.setBackground(new java.awt.Color(204, 204, 204));
        l28.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        l28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l28.setText("Soda Machine");
        l28.setOpaque(true);
        getContentPane().add(l28, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 150, 30));

        l29.setBackground(new java.awt.Color(204, 204, 204));
        l29.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        l29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l29.setText("Header");
        l29.setOpaque(true);
        getContentPane().add(l29, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 110, 30));

        l31.setBackground(new java.awt.Color(204, 204, 204));
        l31.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        l31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l31.setText("Client");
        l31.setOpaque(true);
        getContentPane().add(l31, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, 70, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSalirActionPerformed
        new Menu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jSalirActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
AudioClip sonido;
        sonido= java.applet.Applet.newAudioClip(getClass().getResource("/audio/soda machine.wav"));
        sonido.play();        // TODO add your handling code here:
        l1.setVisible(true);
        l2.setVisible(false);
        l3.setVisible(false);
        l4.setVisible(false);
        l5.setVisible(false);
        l6.setVisible(false);
        l7.setVisible(false);
        l8.setVisible(false);
        l9.setVisible(false);
        l10.setVisible(false);
        l11.setVisible(false);
        l12.setVisible(false);
        l13.setVisible(false);
        l14.setVisible(false);
        l15.setVisible(false);
        l16.setVisible(false);
        l17.setVisible(false);
        l18.setVisible(false);
        l19.setVisible(false);
        l20.setVisible(false);
        l21.setVisible(false);
        l22.setVisible(false);
        l23.setVisible(false);
        l24.setVisible(false);
        l25.setVisible(false);
    }//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
AudioClip sonido;
        sonido= java.applet.Applet.newAudioClip(getClass().getResource("/audio/header.wav"));
        sonido.play();        // TODO add your handling code here:
        l1.setVisible(false);
        l2.setVisible(true);
        l3.setVisible(false);
        l4.setVisible(false);
        l5.setVisible(false);
        l6.setVisible(false);
        l7.setVisible(false);
        l8.setVisible(false);
        l9.setVisible(false);
        l10.setVisible(false);
        l11.setVisible(false);
        l12.setVisible(false);
        l13.setVisible(false);
        l14.setVisible(false);
        l15.setVisible(false);
        l16.setVisible(false);
        l17.setVisible(false);
        l18.setVisible(false);
        l19.setVisible(false);
        l20.setVisible(false);
        l21.setVisible(false);
        l22.setVisible(false);
        l23.setVisible(false);
        l24.setVisible(false);
        l25.setVisible(false);
    }//GEN-LAST:event_b2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
    AudioClip sonido;
        sonido= java.applet.Applet.newAudioClip(getClass().getResource("/audio/plate.wav"));
        sonido.play();    // TODO add your handling code here:
        l1.setVisible(false);
        l2.setVisible(false);
        l3.setVisible(true);
        l4.setVisible(false);
        l5.setVisible(false);
        l6.setVisible(false);
        l7.setVisible(false);
        l8.setVisible(false);
        l9.setVisible(false);
        l10.setVisible(false);
        l11.setVisible(false);
        l12.setVisible(false);
        l13.setVisible(false);
        l14.setVisible(false);
        l15.setVisible(false);
        l16.setVisible(false);
        l17.setVisible(false);
        l18.setVisible(false);
        l19.setVisible(false);
        l20.setVisible(false);
        l21.setVisible(false);
        l22.setVisible(false);
        l23.setVisible(false);
        l24.setVisible(false);
        l25.setVisible(false);
    }//GEN-LAST:event_b3ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
AudioClip sonido;
        sonido= java.applet.Applet.newAudioClip(getClass().getResource("/audio/client.wav"));
        sonido.play();        // TODO add your handling code here:
        l1.setVisible(false);
        l2.setVisible(false);
        l3.setVisible(false);
        l4.setVisible(true);
        l5.setVisible(false);
        l6.setVisible(false);
        l7.setVisible(false);
        l8.setVisible(false);
        l9.setVisible(false);
        l10.setVisible(false);
        l11.setVisible(false);
        l12.setVisible(false);
        l13.setVisible(false);
        l14.setVisible(false);
        l15.setVisible(false);
        l16.setVisible(false);
        l17.setVisible(false);
        l18.setVisible(false);
        l19.setVisible(false);
        l20.setVisible(false);
        l21.setVisible(false);
        l22.setVisible(false);
        l23.setVisible(false);
        l24.setVisible(false);
        l25.setVisible(false);
    }//GEN-LAST:event_b4ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
AudioClip sonido;
        sonido= java.applet.Applet.newAudioClip(getClass().getResource("/audio/shoes.wav"));
        sonido.play();        // TODO add your handling code here:
        l1.setVisible(false);
        l2.setVisible(false);
        l3.setVisible(false);
        l4.setVisible(false);
        l5.setVisible(true);
        l6.setVisible(false);
        l7.setVisible(false);
        l8.setVisible(false);
        l9.setVisible(false);
        l10.setVisible(false);
        l11.setVisible(false);
        l12.setVisible(false);
        l13.setVisible(false);
        l14.setVisible(false);
        l15.setVisible(false);
        l16.setVisible(false);
        l17.setVisible(false);
        l18.setVisible(false);
        l19.setVisible(false);
        l20.setVisible(false);
        l21.setVisible(false);
        l22.setVisible(false);
        l23.setVisible(false);
        l24.setVisible(false);
        l25.setVisible(false);
    }//GEN-LAST:event_b5ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
     AudioClip sonido;
        sonido= java.applet.Applet.newAudioClip(getClass().getResource("/audio/skewers.wav"));
        sonido.play();   // TODO add your handling code here:
        l1.setVisible(false);
        l2.setVisible(false);
        l3.setVisible(false);
        l4.setVisible(false);
        l5.setVisible(false);
        l6.setVisible(true);
        l7.setVisible(false);
        l8.setVisible(false);
        l9.setVisible(false);
        l10.setVisible(false);
        l11.setVisible(false);
        l12.setVisible(false);
        l13.setVisible(false);
        l14.setVisible(false);
        l15.setVisible(false);
        l16.setVisible(false);
        l17.setVisible(false);
        l18.setVisible(false);
        l19.setVisible(false);
        l20.setVisible(false);
        l21.setVisible(false);
        l22.setVisible(false);
        l23.setVisible(false);
        l24.setVisible(false);
        l25.setVisible(false);
    }//GEN-LAST:event_b6ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
AudioClip sonido;
        sonido= java.applet.Applet.newAudioClip(getClass().getResource("/audio/menu.wav"));
        sonido.play();        // TODO add your handling code here:
        l1.setVisible(false);
        l2.setVisible(false);
        l3.setVisible(false);
        l4.setVisible(false);
        l5.setVisible(false);
        l6.setVisible(false);
        l7.setVisible(true);
        l8.setVisible(false);
        l9.setVisible(false);
        l10.setVisible(false);
        l11.setVisible(false);
        l12.setVisible(false);
        l13.setVisible(false);
        l14.setVisible(false);
        l15.setVisible(false);
        l16.setVisible(false);
        l17.setVisible(false);
        l18.setVisible(false);
        l19.setVisible(false);
        l20.setVisible(false);
        l21.setVisible(false);
        l22.setVisible(false);
        l23.setVisible(false);
        l24.setVisible(false);
        l25.setVisible(false);
    }//GEN-LAST:event_b7ActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
AudioClip sonido;
        sonido= java.applet.Applet.newAudioClip(getClass().getResource("/audio/bar.wav"));
        sonido.play();        // TODO add your handling code here:
        l1.setVisible(false);
        l2.setVisible(false);
        l3.setVisible(false);
        l4.setVisible(false);
        l5.setVisible(false);
        l6.setVisible(false);
        l7.setVisible(false);
        l8.setVisible(true);
        l9.setVisible(false);
        l10.setVisible(false);
        l11.setVisible(false);
        l12.setVisible(false);
        l13.setVisible(false);
        l14.setVisible(false);
        l15.setVisible(false);
        l16.setVisible(false);
        l17.setVisible(false);
        l18.setVisible(false);
        l19.setVisible(false);
        l20.setVisible(false);
        l21.setVisible(false);
        l22.setVisible(false);
        l23.setVisible(false);
        l24.setVisible(false);
        l25.setVisible(false);
    }//GEN-LAST:event_b8ActionPerformed

    private void b9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b9ActionPerformed
AudioClip sonido;
        sonido= java.applet.Applet.newAudioClip(getClass().getResource("/audio/cap.wav"));
        sonido.play();        // TODO add your handling code here:
        l1.setVisible(false);
        l2.setVisible(false);
        l3.setVisible(false);
        l4.setVisible(false);
        l5.setVisible(false);
        l6.setVisible(false);
        l7.setVisible(false);
        l8.setVisible(false);
        l9.setVisible(true);
        l10.setVisible(false);
        l11.setVisible(false);
        l12.setVisible(false);
        l13.setVisible(false);
        l14.setVisible(false);
        l15.setVisible(false);
        l16.setVisible(false);
        l17.setVisible(false);
        l18.setVisible(false);
        l19.setVisible(false);
        l20.setVisible(false);
        l21.setVisible(false);
        l22.setVisible(false);
        l23.setVisible(false);
        l24.setVisible(false);
        l25.setVisible(false);
    }//GEN-LAST:event_b9ActionPerformed

    private void b10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b10ActionPerformed
AudioClip sonido;
        sonido= java.applet.Applet.newAudioClip(getClass().getResource("/audio/dish.wav"));
        sonido.play();        // TODO add your handling code here:
        l1.setVisible(false);
        l2.setVisible(false);
        l3.setVisible(false);
        l4.setVisible(false);
        l5.setVisible(false);
        l6.setVisible(false);
        l7.setVisible(false);
        l8.setVisible(false);
        l9.setVisible(false);
        l10.setVisible(true);
        l11.setVisible(false);
        l12.setVisible(false);
        l13.setVisible(false);
        l14.setVisible(false);
        l15.setVisible(false);
        l16.setVisible(false);
        l17.setVisible(false);
        l18.setVisible(false);
        l19.setVisible(false);
        l20.setVisible(false);
        l21.setVisible(false);
        l22.setVisible(false);
        l23.setVisible(false);
        l24.setVisible(false);
        l25.setVisible(false);
    }//GEN-LAST:event_b10ActionPerformed

    private void b11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b11ActionPerformed
AudioClip sonido;
        sonido= java.applet.Applet.newAudioClip(getClass().getResource("/audio/cashier.wav"));
        sonido.play();        // TODO add your handling code here:
        l1.setVisible(false);
        l2.setVisible(false);
        l3.setVisible(false);
        l4.setVisible(false);
        l5.setVisible(false);
        l6.setVisible(false);
        l7.setVisible(false);
        l8.setVisible(false);
        l9.setVisible(false);
        l10.setVisible(false);
        l11.setVisible(true);
        l12.setVisible(false);
        l13.setVisible(false);
        l14.setVisible(false);
        l15.setVisible(false);
        l16.setVisible(false);
        l17.setVisible(false);
        l18.setVisible(false);
        l19.setVisible(false);
        l20.setVisible(false);
        l21.setVisible(false);
        l22.setVisible(false);
        l23.setVisible(false);
        l24.setVisible(false);
        l25.setVisible(false);
    }//GEN-LAST:event_b11ActionPerformed

    private void b12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b12ActionPerformed
AudioClip sonido;
        sonido= java.applet.Applet.newAudioClip(getClass().getResource("/audio/fried chicken.wav"));
        sonido.play();        // TODO add your handling code here:
        l1.setVisible(false);
        l2.setVisible(false);
        l3.setVisible(false);
        l4.setVisible(false);
        l5.setVisible(false);
        l6.setVisible(false);
        l7.setVisible(false);
        l8.setVisible(false);
        l9.setVisible(false);
        l10.setVisible(false);
        l11.setVisible(false);
        l12.setVisible(true);
        l13.setVisible(false);
        l14.setVisible(false);
        l15.setVisible(false);
        l16.setVisible(false);
        l17.setVisible(false);
        l18.setVisible(false);
        l19.setVisible(false);
        l20.setVisible(false);
        l21.setVisible(false);
        l22.setVisible(false);
        l23.setVisible(false);
        l24.setVisible(false);
        l25.setVisible(false);
    }//GEN-LAST:event_b12ActionPerformed

    private void b13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b13ActionPerformed
AudioClip sonido;
        sonido= java.applet.Applet.newAudioClip(getClass().getResource("/audio/beverage.wav"));
        sonido.play();        // TODO add your handling code here:
        l1.setVisible(false);
        l2.setVisible(false);
        l3.setVisible(false);
        l4.setVisible(false);
        l5.setVisible(false);
        l6.setVisible(false);
        l7.setVisible(false);
        l8.setVisible(false);
        l9.setVisible(false);
        l10.setVisible(false);
        l11.setVisible(false);
        l12.setVisible(false);
        l13.setVisible(true);
        l14.setVisible(false);
        l15.setVisible(false);
        l16.setVisible(false);
        l17.setVisible(false);
        l18.setVisible(false);
        l19.setVisible(false);
        l20.setVisible(false);
        l21.setVisible(false);
        l22.setVisible(false);
        l23.setVisible(false);
        l24.setVisible(false);
        l25.setVisible(false);
    }//GEN-LAST:event_b13ActionPerformed

    private void b14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b14ActionPerformed
  AudioClip sonido;
        sonido= java.applet.Applet.newAudioClip(getClass().getResource("/audio/dessert.wav"));
        sonido.play();      // TODO add your handling code here:
        l1.setVisible(false);
        l2.setVisible(false);
        l3.setVisible(false);
        l4.setVisible(false);
        l5.setVisible(false);
        l6.setVisible(false);
        l7.setVisible(false);
        l8.setVisible(false);
        l9.setVisible(false);
        l10.setVisible(false);
        l11.setVisible(false);
        l12.setVisible(false);
        l13.setVisible(false);
        l14.setVisible(true);
        l15.setVisible(false);
        l16.setVisible(false);
        l17.setVisible(false);
        l18.setVisible(false);
        l19.setVisible(false);
        l20.setVisible(false);
        l21.setVisible(false);
        l22.setVisible(false);
        l23.setVisible(false);
        l24.setVisible(false);
        l25.setVisible(false);
    }//GEN-LAST:event_b14ActionPerformed

    private void b15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b15ActionPerformed
AudioClip sonido;
        sonido= java.applet.Applet.newAudioClip(getClass().getResource("/audio/table.wav"));
        sonido.play();        // TODO add your handling code here:
        l1.setVisible(false);
        l2.setVisible(false);
        l3.setVisible(false);
        l4.setVisible(false);
        l5.setVisible(false);
        l6.setVisible(false);
        l7.setVisible(false);
        l8.setVisible(false);
        l9.setVisible(false);
        l10.setVisible(false);
        l11.setVisible(false);
        l12.setVisible(false);
        l13.setVisible(false);
        l14.setVisible(false);
        l15.setVisible(true);
        l16.setVisible(false);
        l17.setVisible(false);
        l18.setVisible(false);
        l19.setVisible(false);
        l20.setVisible(false);
        l21.setVisible(false);
        l22.setVisible(false);
        l23.setVisible(false);
        l24.setVisible(false);
        l25.setVisible(false);
    }//GEN-LAST:event_b15ActionPerformed

    private void b16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b16ActionPerformed
AudioClip sonido;
        sonido= java.applet.Applet.newAudioClip(getClass().getResource("/audio/nuggets.wav"));
        sonido.play();        // TODO add your handling code here:
        l1.setVisible(false);
        l2.setVisible(false);
        l3.setVisible(false);
        l4.setVisible(false);
        l5.setVisible(false);
        l6.setVisible(false);
        l7.setVisible(false);
        l8.setVisible(false);
        l9.setVisible(false);
        l10.setVisible(false);
        l11.setVisible(false);
        l12.setVisible(false);
        l13.setVisible(false);
        l14.setVisible(false);
        l15.setVisible(false);
        l16.setVisible(true);
        l17.setVisible(false);
        l18.setVisible(false);
        l19.setVisible(false);
        l20.setVisible(false);
        l21.setVisible(false);
        l22.setVisible(false);
        l23.setVisible(false);
        l24.setVisible(false);
        l25.setVisible(false);
    }//GEN-LAST:event_b16ActionPerformed

    private void b17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b17ActionPerformed
AudioClip sonido;
        sonido= java.applet.Applet.newAudioClip(getClass().getResource("/audio/salad.wav"));
        sonido.play();        // TODO add your handling code here:
        l1.setVisible(false);
        l2.setVisible(false);
        l3.setVisible(false);
        l4.setVisible(false);
        l5.setVisible(false);
        l6.setVisible(false);
        l7.setVisible(false);
        l8.setVisible(false);
        l9.setVisible(false);
        l10.setVisible(false);
        l11.setVisible(false);
        l12.setVisible(false);
        l13.setVisible(false);
        l14.setVisible(false);
        l15.setVisible(false);
        l16.setVisible(false);
        l17.setVisible(true);
        l18.setVisible(false);
        l19.setVisible(false);
        l20.setVisible(false);
        l21.setVisible(false);
        l22.setVisible(false);
        l23.setVisible(false);
        l24.setVisible(false);
        l25.setVisible(false);
    }//GEN-LAST:event_b17ActionPerformed

    private void b18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b18ActionPerformed
AudioClip sonido;
        sonido= java.applet.Applet.newAudioClip(getClass().getResource("/audio/floor.wav"));
        sonido.play();        // TODO add your handling code here:
        l1.setVisible(false);
        l2.setVisible(false);
        l3.setVisible(false);
        l4.setVisible(false);
        l5.setVisible(false);
        l6.setVisible(false);
        l7.setVisible(false);
        l8.setVisible(false);
        l9.setVisible(false);
        l10.setVisible(false);
        l11.setVisible(false);
        l12.setVisible(false);
        l13.setVisible(false);
        l14.setVisible(false);
        l15.setVisible(false);
        l16.setVisible(false);
        l17.setVisible(false);
        l18.setVisible(true);
        l19.setVisible(false);
        l20.setVisible(false);
        l21.setVisible(false);
        l22.setVisible(false);
        l23.setVisible(false);
        l24.setVisible(false);
        l25.setVisible(false);
    }//GEN-LAST:event_b18ActionPerformed

    private void b19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b19ActionPerformed
AudioClip sonido;
        sonido= java.applet.Applet.newAudioClip(getClass().getResource("/audio/bags.wav"));
        sonido.play();        l1.setVisible(false);
        l2.setVisible(false);
        l3.setVisible(false);
        l4.setVisible(false);
        l5.setVisible(false);
        l6.setVisible(false);
        l7.setVisible(false);
        l8.setVisible(false);
        l9.setVisible(false);
        l10.setVisible(false);
        l11.setVisible(false);
        l12.setVisible(false);
        l13.setVisible(false);
        l14.setVisible(false);
        l15.setVisible(false);
        l16.setVisible(false);
        l17.setVisible(false);
        l18.setVisible(false);
        l19.setVisible(true);
        l20.setVisible(false);
        l21.setVisible(false);
        l22.setVisible(false);
        l23.setVisible(false);
        l24.setVisible(false);
        l25.setVisible(false);
    }//GEN-LAST:event_b19ActionPerformed

    private void b20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b20ActionPerformed
AudioClip sonido;
        sonido= java.applet.Applet.newAudioClip(getClass().getResource("/audio/french fries.wav"));
        sonido.play();        // TODO add your handling code here:
        l1.setVisible(false);
        l2.setVisible(false);
        l3.setVisible(false);
        l4.setVisible(false);
        l5.setVisible(false);
        l6.setVisible(false);
        l7.setVisible(false);
        l8.setVisible(false);
        l9.setVisible(false);
        l10.setVisible(false);
        l11.setVisible(false);
        l12.setVisible(false);
        l13.setVisible(false);
        l14.setVisible(false);
        l15.setVisible(false);
        l16.setVisible(false);
        l17.setVisible(false);
        l18.setVisible(false);
        l19.setVisible(false);
        l20.setVisible(true);
        l21.setVisible(false);
        l22.setVisible(false);
        l23.setVisible(false);
        l24.setVisible(false);
        l25.setVisible(false);
    }//GEN-LAST:event_b20ActionPerformed

    private void b21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b21ActionPerformed
AudioClip sonido;
        sonido= java.applet.Applet.newAudioClip(getClass().getResource("/audio/ad.wav"));
        sonido.play();        // TODO add your handling code here:
        l1.setVisible(false);
        l2.setVisible(false);
        l3.setVisible(false);
        l4.setVisible(false);
        l5.setVisible(false);
        l6.setVisible(false);
        l7.setVisible(false);
        l8.setVisible(false);
        l9.setVisible(false);
        l10.setVisible(false);
        l11.setVisible(false);
        l12.setVisible(false);
        l13.setVisible(false);
        l14.setVisible(false);
        l15.setVisible(false);
        l16.setVisible(false);
        l17.setVisible(false);
        l18.setVisible(false);
        l19.setVisible(false);
        l20.setVisible(false);
        l21.setVisible(true);
        l22.setVisible(false);
        l23.setVisible(false);
        l24.setVisible(false);
        l25.setVisible(false);
    }//GEN-LAST:event_b21ActionPerformed

    private void b22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b22ActionPerformed
AudioClip sonido;
        sonido= java.applet.Applet.newAudioClip(getClass().getResource("/audio/computer.wav"));
        sonido.play();        // TODO add your handling code here:
        l1.setVisible(false);
        l2.setVisible(false);
        l3.setVisible(false);
        l4.setVisible(false);
        l5.setVisible(false);
        l6.setVisible(false);
        l7.setVisible(false);
        l8.setVisible(false);
        l9.setVisible(false);
        l10.setVisible(false);
        l11.setVisible(false);
        l12.setVisible(false);
        l13.setVisible(false);
        l14.setVisible(false);
        l15.setVisible(false);
        l16.setVisible(false);
        l17.setVisible(false);
        l18.setVisible(false);
        l19.setVisible(false);
        l20.setVisible(false);
        l21.setVisible(false);
        l22.setVisible(true);
        l23.setVisible(false);
        l24.setVisible(false);
        l25.setVisible(false);
    }//GEN-LAST:event_b22ActionPerformed

    private void b23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b23ActionPerformed
AudioClip sonido;
        sonido= java.applet.Applet.newAudioClip(getClass().getResource("/audio/chair.wav"));
        sonido.play();        // TODO add your handling code here:
        l1.setVisible(false);
        l2.setVisible(false);
        l3.setVisible(false);
        l4.setVisible(false);
        l5.setVisible(false);
        l6.setVisible(false);
        l7.setVisible(false);
        l8.setVisible(false);
        l9.setVisible(false);
        l10.setVisible(false);
        l11.setVisible(false);
        l12.setVisible(false);
        l13.setVisible(false);
        l14.setVisible(false);
        l15.setVisible(false);
        l16.setVisible(false);
        l17.setVisible(false);
        l18.setVisible(false);
        l19.setVisible(false);
        l20.setVisible(false);
        l21.setVisible(false);
        l22.setVisible(false);
        l23.setVisible(true);
        l24.setVisible(false);
        l25.setVisible(false);
    }//GEN-LAST:event_b23ActionPerformed

    private void b24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b24ActionPerformed
AudioClip sonido;
        sonido= java.applet.Applet.newAudioClip(getClass().getResource("/audio/burger.wav"));
        sonido.play();        // TODO add your handling code here:
        l1.setVisible(false);
        l2.setVisible(false);
        l3.setVisible(false);
        l4.setVisible(false);
        l5.setVisible(false);
        l6.setVisible(false);
        l7.setVisible(false);
        l8.setVisible(false);
        l9.setVisible(false);
        l10.setVisible(false);
        l11.setVisible(false);
        l12.setVisible(false);
        l13.setVisible(false);
        l14.setVisible(false);
        l15.setVisible(false);
        l16.setVisible(false);
        l17.setVisible(false);
        l18.setVisible(false);
        l19.setVisible(false);
        l20.setVisible(false);
        l21.setVisible(false);
        l22.setVisible(false);
        l23.setVisible(false);
        l24.setVisible(true);
        l25.setVisible(false);
    }//GEN-LAST:event_b24ActionPerformed

    private void b25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b25ActionPerformed
AudioClip sonido;
        sonido= java.applet.Applet.newAudioClip(getClass().getResource("/audio/bowl.wav"));
        sonido.play();        // TODO add your handling code here:
        l1.setVisible(false);
        l2.setVisible(false);
        l3.setVisible(false);
        l4.setVisible(false);
        l5.setVisible(false);
        l6.setVisible(false);
        l7.setVisible(false);
        l8.setVisible(false);
        l9.setVisible(false);
        l10.setVisible(false);
        l11.setVisible(false);
        l12.setVisible(false);
        l13.setVisible(false);
        l14.setVisible(false);
        l15.setVisible(false);
        l16.setVisible(false);
        l17.setVisible(false);
        l18.setVisible(false);
        l19.setVisible(false);
        l20.setVisible(false);
        l21.setVisible(false);
        l22.setVisible(false);
        l23.setVisible(false);
        l24.setVisible(false);
        l25.setVisible(true);
    }//GEN-LAST:event_b25ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ComidaRapida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ComidaRapida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ComidaRapida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ComidaRapida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ComidaRapida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b10;
    private javax.swing.JButton b11;
    private javax.swing.JButton b12;
    private javax.swing.JButton b13;
    private javax.swing.JButton b14;
    private javax.swing.JButton b15;
    private javax.swing.JButton b16;
    private javax.swing.JButton b17;
    private javax.swing.JButton b18;
    private javax.swing.JButton b19;
    private javax.swing.JButton b2;
    private javax.swing.JButton b20;
    private javax.swing.JButton b21;
    private javax.swing.JButton b22;
    private javax.swing.JButton b23;
    private javax.swing.JButton b24;
    private javax.swing.JButton b25;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.JLabel jFondo;
    private javax.swing.JButton jSalir;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l10;
    private javax.swing.JLabel l11;
    private javax.swing.JLabel l12;
    private javax.swing.JLabel l13;
    private javax.swing.JLabel l14;
    private javax.swing.JLabel l15;
    private javax.swing.JLabel l16;
    private javax.swing.JLabel l17;
    private javax.swing.JLabel l18;
    private javax.swing.JLabel l19;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l20;
    private javax.swing.JLabel l21;
    private javax.swing.JLabel l22;
    private javax.swing.JLabel l23;
    private javax.swing.JLabel l24;
    private javax.swing.JLabel l25;
    private javax.swing.JLabel l26;
    private javax.swing.JLabel l27;
    private javax.swing.JLabel l28;
    private javax.swing.JLabel l29;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l31;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel l5;
    private javax.swing.JLabel l6;
    private javax.swing.JLabel l7;
    private javax.swing.JLabel l8;
    private javax.swing.JLabel l9;
    // End of variables declaration//GEN-END:variables
}
