package Modulos;

import java.applet.AudioClip;

public class Joyeria extends javax.swing.JFrame {

    /**
     * Creates new form Joyeria
     */
    public Joyeria() {
        initComponents();
        this.setSize(887,500);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        A1.setVisible(false);
        A2.setVisible(false);
        A3.setVisible(false);
        A4.setVisible(false);
        A5.setVisible(false);
        A6.setVisible(false);
        A7.setVisible(false);
        A8.setVisible(false);
        A9.setVisible(false);
        A10.setVisible(false);
        A11.setVisible(false);
        A12.setVisible(false);
        A13.setVisible(false);
        A14.setVisible(false);
        A15.setVisible(false);
        A16.setVisible(false);
        A17.setVisible(false);
        A18.setVisible(false);
        A19.setVisible(false);
        A20.setVisible(false);
        A21.setVisible(false);
        A22.setVisible(false);
        A23.setVisible(false);
        A24.setVisible(false);
        A25.setVisible(false);
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jButton40 = new javax.swing.JButton();
        jButton41 = new javax.swing.JButton();
        jButton42 = new javax.swing.JButton();
        jButton43 = new javax.swing.JButton();
        jButton44 = new javax.swing.JButton();
        jButton45 = new javax.swing.JButton();
        jButton46 = new javax.swing.JButton();
        jButton47 = new javax.swing.JButton();
        A1 = new javax.swing.JLabel();
        A2 = new javax.swing.JLabel();
        A3 = new javax.swing.JLabel();
        A13 = new javax.swing.JLabel();
        A14 = new javax.swing.JLabel();
        A4 = new javax.swing.JLabel();
        A5 = new javax.swing.JLabel();
        A6 = new javax.swing.JLabel();
        A7 = new javax.swing.JLabel();
        A8 = new javax.swing.JLabel();
        A9 = new javax.swing.JLabel();
        A10 = new javax.swing.JLabel();
        A11 = new javax.swing.JLabel();
        A12 = new javax.swing.JLabel();
        A25 = new javax.swing.JLabel();
        A15 = new javax.swing.JLabel();
        A16 = new javax.swing.JLabel();
        A23 = new javax.swing.JLabel();
        A22 = new javax.swing.JLabel();
        A21 = new javax.swing.JLabel();
        A20 = new javax.swing.JLabel();
        A19 = new javax.swing.JLabel();
        A18 = new javax.swing.JLabel();
        A17 = new javax.swing.JLabel();
        A24 = new javax.swing.JLabel();
        jSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jButton23.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton23.setForeground(new java.awt.Color(255, 255, 255));
        jButton23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/45.png"))); // NOI18N
        jButton23.setText("1");
        jButton23.setBorder(null);
        jButton23.setBorderPainted(false);
        jButton23.setContentAreaFilled(false);
        jButton23.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton23.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton23.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/35.png"))); // NOI18N
        jButton23.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/40.png"))); // NOI18N
        jButton23.setVerifyInputWhenFocusTarget(false);
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton23);
        jButton23.setBounds(120, 190, 40, 31);

        jButton24.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton24.setForeground(new java.awt.Color(255, 255, 255));
        jButton24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/45.png"))); // NOI18N
        jButton24.setText("3");
        jButton24.setBorder(null);
        jButton24.setBorderPainted(false);
        jButton24.setContentAreaFilled(false);
        jButton24.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton24.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton24.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/35.png"))); // NOI18N
        jButton24.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/40.png"))); // NOI18N
        jButton24.setVerifyInputWhenFocusTarget(false);
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton24);
        jButton24.setBounds(90, 410, 40, 31);

        jButton25.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton25.setForeground(new java.awt.Color(255, 255, 255));
        jButton25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/45.png"))); // NOI18N
        jButton25.setText("5");
        jButton25.setBorder(null);
        jButton25.setBorderPainted(false);
        jButton25.setContentAreaFilled(false);
        jButton25.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton25.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton25.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/35.png"))); // NOI18N
        jButton25.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/40.png"))); // NOI18N
        jButton25.setVerifyInputWhenFocusTarget(false);
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton25);
        jButton25.setBounds(240, 300, 40, 31);

        jButton26.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton26.setForeground(new java.awt.Color(255, 255, 255));
        jButton26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/45.png"))); // NOI18N
        jButton26.setText("15");
        jButton26.setBorder(null);
        jButton26.setBorderPainted(false);
        jButton26.setContentAreaFilled(false);
        jButton26.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton26.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton26.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/35.png"))); // NOI18N
        jButton26.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/40.png"))); // NOI18N
        jButton26.setVerifyInputWhenFocusTarget(false);
        jButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton26ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton26);
        jButton26.setBounds(310, 300, 40, 31);

        jButton27.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton27.setForeground(new java.awt.Color(255, 255, 255));
        jButton27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/45.png"))); // NOI18N
        jButton27.setText("16");
        jButton27.setBorder(null);
        jButton27.setBorderPainted(false);
        jButton27.setContentAreaFilled(false);
        jButton27.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton27.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton27.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/35.png"))); // NOI18N
        jButton27.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/40.png"))); // NOI18N
        jButton27.setVerifyInputWhenFocusTarget(false);
        jButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton27ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton27);
        jButton27.setBounds(370, 300, 40, 31);

        jButton28.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton28.setForeground(new java.awt.Color(255, 255, 255));
        jButton28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/45.png"))); // NOI18N
        jButton28.setText("6");
        jButton28.setBorder(null);
        jButton28.setBorderPainted(false);
        jButton28.setContentAreaFilled(false);
        jButton28.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton28.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton28.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/35.png"))); // NOI18N
        jButton28.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/40.png"))); // NOI18N
        jButton28.setVerifyInputWhenFocusTarget(false);
        jButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton28ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton28);
        jButton28.setBounds(320, 190, 40, 31);

        jButton29.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton29.setForeground(new java.awt.Color(255, 255, 255));
        jButton29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/45.png"))); // NOI18N
        jButton29.setText("17");
        jButton29.setBorder(null);
        jButton29.setBorderPainted(false);
        jButton29.setContentAreaFilled(false);
        jButton29.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton29.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton29.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/35.png"))); // NOI18N
        jButton29.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/40.png"))); // NOI18N
        jButton29.setVerifyInputWhenFocusTarget(false);
        jButton29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton29ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton29);
        jButton29.setBounds(420, 300, 40, 31);

        jButton30.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton30.setForeground(new java.awt.Color(255, 255, 255));
        jButton30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/45.png"))); // NOI18N
        jButton30.setText("18");
        jButton30.setBorder(null);
        jButton30.setBorderPainted(false);
        jButton30.setContentAreaFilled(false);
        jButton30.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton30.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton30.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/35.png"))); // NOI18N
        jButton30.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/40.png"))); // NOI18N
        jButton30.setVerifyInputWhenFocusTarget(false);
        jButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton30ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton30);
        jButton30.setBounds(470, 300, 40, 31);

        jButton31.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton31.setForeground(new java.awt.Color(255, 255, 255));
        jButton31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/45.png"))); // NOI18N
        jButton31.setText("19");
        jButton31.setBorder(null);
        jButton31.setBorderPainted(false);
        jButton31.setContentAreaFilled(false);
        jButton31.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton31.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton31.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/35.png"))); // NOI18N
        jButton31.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/40.png"))); // NOI18N
        jButton31.setVerifyInputWhenFocusTarget(false);
        jButton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton31ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton31);
        jButton31.setBounds(520, 300, 40, 31);

        jButton32.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton32.setForeground(new java.awt.Color(255, 255, 255));
        jButton32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/45.png"))); // NOI18N
        jButton32.setText("20");
        jButton32.setBorder(null);
        jButton32.setBorderPainted(false);
        jButton32.setContentAreaFilled(false);
        jButton32.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton32.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton32.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/35.png"))); // NOI18N
        jButton32.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/40.png"))); // NOI18N
        jButton32.setVerifyInputWhenFocusTarget(false);
        jButton32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton32ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton32);
        jButton32.setBounds(570, 300, 40, 31);

        jButton33.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton33.setForeground(new java.awt.Color(255, 255, 255));
        jButton33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/45.png"))); // NOI18N
        jButton33.setText("21");
        jButton33.setBorder(null);
        jButton33.setBorderPainted(false);
        jButton33.setContentAreaFilled(false);
        jButton33.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton33.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton33.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/35.png"))); // NOI18N
        jButton33.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/40.png"))); // NOI18N
        jButton33.setVerifyInputWhenFocusTarget(false);
        jButton33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton33ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton33);
        jButton33.setBounds(620, 300, 40, 31);

        jButton34.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton34.setForeground(new java.awt.Color(255, 255, 255));
        jButton34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/45.png"))); // NOI18N
        jButton34.setText("22");
        jButton34.setBorder(null);
        jButton34.setBorderPainted(false);
        jButton34.setContentAreaFilled(false);
        jButton34.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton34.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton34.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/35.png"))); // NOI18N
        jButton34.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/40.png"))); // NOI18N
        jButton34.setVerifyInputWhenFocusTarget(false);
        jButton34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton34ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton34);
        jButton34.setBounds(670, 300, 40, 31);

        jButton35.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton35.setForeground(new java.awt.Color(255, 255, 255));
        jButton35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/45.png"))); // NOI18N
        jButton35.setText("14");
        jButton35.setBorder(null);
        jButton35.setBorderPainted(false);
        jButton35.setContentAreaFilled(false);
        jButton35.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton35.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton35.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/35.png"))); // NOI18N
        jButton35.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/40.png"))); // NOI18N
        jButton35.setVerifyInputWhenFocusTarget(false);
        jButton35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton35ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton35);
        jButton35.setBounds(720, 240, 40, 31);

        jButton36.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton36.setForeground(new java.awt.Color(255, 255, 255));
        jButton36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/45.png"))); // NOI18N
        jButton36.setText("13");
        jButton36.setBorder(null);
        jButton36.setBorderPainted(false);
        jButton36.setContentAreaFilled(false);
        jButton36.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton36.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton36.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/35.png"))); // NOI18N
        jButton36.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/40.png"))); // NOI18N
        jButton36.setVerifyInputWhenFocusTarget(false);
        jButton36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton36ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton36);
        jButton36.setBounds(650, 200, 40, 31);

        jButton37.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton37.setForeground(new java.awt.Color(255, 255, 255));
        jButton37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/45.png"))); // NOI18N
        jButton37.setText("12");
        jButton37.setBorder(null);
        jButton37.setBorderPainted(false);
        jButton37.setContentAreaFilled(false);
        jButton37.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton37.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton37.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/35.png"))); // NOI18N
        jButton37.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/40.png"))); // NOI18N
        jButton37.setVerifyInputWhenFocusTarget(false);
        jButton37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton37ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton37);
        jButton37.setBounds(590, 190, 40, 31);

        jButton38.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton38.setForeground(new java.awt.Color(255, 255, 255));
        jButton38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/45.png"))); // NOI18N
        jButton38.setText("11");
        jButton38.setBorder(null);
        jButton38.setBorderPainted(false);
        jButton38.setContentAreaFilled(false);
        jButton38.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton38.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton38.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/35.png"))); // NOI18N
        jButton38.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/40.png"))); // NOI18N
        jButton38.setVerifyInputWhenFocusTarget(false);
        jButton38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton38ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton38);
        jButton38.setBounds(540, 180, 40, 31);

        jButton39.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton39.setForeground(new java.awt.Color(255, 255, 255));
        jButton39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/45.png"))); // NOI18N
        jButton39.setText("10");
        jButton39.setToolTipText("");
        jButton39.setBorder(null);
        jButton39.setBorderPainted(false);
        jButton39.setContentAreaFilled(false);
        jButton39.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton39.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton39.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/35.png"))); // NOI18N
        jButton39.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/40.png"))); // NOI18N
        jButton39.setVerifyInputWhenFocusTarget(false);
        jButton39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton39ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton39);
        jButton39.setBounds(500, 190, 40, 31);

        jButton40.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton40.setForeground(new java.awt.Color(255, 255, 255));
        jButton40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/45.png"))); // NOI18N
        jButton40.setText("9");
        jButton40.setBorder(null);
        jButton40.setBorderPainted(false);
        jButton40.setContentAreaFilled(false);
        jButton40.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton40.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton40.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/35.png"))); // NOI18N
        jButton40.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/40.png"))); // NOI18N
        jButton40.setVerifyInputWhenFocusTarget(false);
        jButton40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton40ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton40);
        jButton40.setBounds(460, 190, 40, 31);

        jButton41.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton41.setForeground(new java.awt.Color(255, 255, 255));
        jButton41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/45.png"))); // NOI18N
        jButton41.setText("8");
        jButton41.setBorder(null);
        jButton41.setBorderPainted(false);
        jButton41.setContentAreaFilled(false);
        jButton41.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton41.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton41.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/35.png"))); // NOI18N
        jButton41.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/40.png"))); // NOI18N
        jButton41.setVerifyInputWhenFocusTarget(false);
        jButton41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton41ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton41);
        jButton41.setBounds(420, 180, 40, 31);

        jButton42.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton42.setForeground(new java.awt.Color(255, 255, 255));
        jButton42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/45.png"))); // NOI18N
        jButton42.setText("7");
        jButton42.setBorder(null);
        jButton42.setBorderPainted(false);
        jButton42.setContentAreaFilled(false);
        jButton42.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton42.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton42.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/35.png"))); // NOI18N
        jButton42.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/40.png"))); // NOI18N
        jButton42.setVerifyInputWhenFocusTarget(false);
        jButton42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton42ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton42);
        jButton42.setBounds(370, 190, 40, 31);

        jButton43.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton43.setForeground(new java.awt.Color(255, 255, 255));
        jButton43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/45.png"))); // NOI18N
        jButton43.setText("2");
        jButton43.setBorder(null);
        jButton43.setBorderPainted(false);
        jButton43.setContentAreaFilled(false);
        jButton43.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton43.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton43.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/35.png"))); // NOI18N
        jButton43.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/40.png"))); // NOI18N
        jButton43.setVerifyInputWhenFocusTarget(false);
        jButton43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton43ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton43);
        jButton43.setBounds(230, 110, 40, 31);

        jButton44.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton44.setForeground(new java.awt.Color(255, 255, 255));
        jButton44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/45.png"))); // NOI18N
        jButton44.setText("25");
        jButton44.setBorder(null);
        jButton44.setBorderPainted(false);
        jButton44.setContentAreaFilled(false);
        jButton44.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton44.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton44.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/35.png"))); // NOI18N
        jButton44.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/40.png"))); // NOI18N
        jButton44.setVerifyInputWhenFocusTarget(false);
        jButton44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton44ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton44);
        jButton44.setBounds(520, 100, 40, 31);

        jButton45.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton45.setForeground(new java.awt.Color(255, 255, 255));
        jButton45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/45.png"))); // NOI18N
        jButton45.setText("4");
        jButton45.setBorder(null);
        jButton45.setBorderPainted(false);
        jButton45.setContentAreaFilled(false);
        jButton45.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton45.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton45.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/35.png"))); // NOI18N
        jButton45.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/40.png"))); // NOI18N
        jButton45.setVerifyInputWhenFocusTarget(false);
        jButton45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton45ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton45);
        jButton45.setBounds(230, 380, 40, 31);

        jButton46.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton46.setForeground(new java.awt.Color(255, 255, 255));
        jButton46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/45.png"))); // NOI18N
        jButton46.setText("23");
        jButton46.setBorder(null);
        jButton46.setBorderPainted(false);
        jButton46.setContentAreaFilled(false);
        jButton46.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton46.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton46.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/35.png"))); // NOI18N
        jButton46.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/40.png"))); // NOI18N
        jButton46.setVerifyInputWhenFocusTarget(false);
        jButton46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton46ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton46);
        jButton46.setBounds(490, 390, 40, 31);

        jButton47.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton47.setForeground(new java.awt.Color(255, 255, 255));
        jButton47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/45.png"))); // NOI18N
        jButton47.setText("24");
        jButton47.setBorder(null);
        jButton47.setBorderPainted(false);
        jButton47.setContentAreaFilled(false);
        jButton47.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton47.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton47.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/35.png"))); // NOI18N
        jButton47.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/40.png"))); // NOI18N
        jButton47.setVerifyInputWhenFocusTarget(false);
        jButton47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton47ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton47);
        jButton47.setBounds(800, 350, 40, 31);

        A1.setBackground(new java.awt.Color(204, 204, 204));
        A1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        A1.setText("CASH REGISTER");
        A1.setOpaque(true);
        jPanel1.add(A1);
        A1.setBounds(0, 160, 200, 30);

        A2.setBackground(new java.awt.Color(204, 204, 204));
        A2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        A2.setText("PLANT");
        A2.setOpaque(true);
        jPanel1.add(A2);
        A2.setBounds(140, 430, 90, 30);

        A3.setBackground(new java.awt.Color(204, 204, 204));
        A3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        A3.setText("TABLE");
        A3.setOpaque(true);
        jPanel1.add(A3);
        A3.setBounds(280, 390, 100, 30);

        A13.setBackground(new java.awt.Color(204, 204, 204));
        A13.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        A13.setText("LOGO");
        A13.setOpaque(true);
        jPanel1.add(A13);
        A13.setBounds(540, 400, 90, 30);

        A14.setBackground(new java.awt.Color(204, 204, 204));
        A14.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        A14.setText("SALESWOMAN");
        A14.setOpaque(true);
        jPanel1.add(A14);
        A14.setBounds(610, 370, 190, 30);

        A4.setBackground(new java.awt.Color(204, 204, 204));
        A4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        A4.setText("CROWN");
        A4.setOpaque(true);
        jPanel1.add(A4);
        A4.setBounds(160, 340, 110, 30);

        A5.setBackground(new java.awt.Color(204, 204, 204));
        A5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        A5.setText("CLOCK");
        A5.setOpaque(true);
        jPanel1.add(A5);
        A5.setBounds(230, 340, 110, 30);

        A6.setBackground(new java.awt.Color(204, 204, 204));
        A6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        A6.setText("EARRINGS ");
        A6.setOpaque(true);
        jPanel1.add(A6);
        A6.setBounds(300, 340, 150, 30);

        A7.setBackground(new java.awt.Color(204, 204, 204));
        A7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        A7.setText("NECKLACE ");
        A7.setOpaque(true);
        jPanel1.add(A7);
        A7.setBounds(360, 340, 160, 30);

        A8.setBackground(new java.awt.Color(204, 204, 204));
        A8.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        A8.setText("SLOPES ");
        A8.setOpaque(true);
        jPanel1.add(A8);
        A8.setBounds(430, 340, 120, 30);

        A9.setBackground(new java.awt.Color(204, 204, 204));
        A9.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        A9.setText("BRACELET");
        A9.setOpaque(true);
        jPanel1.add(A9);
        A9.setBounds(490, 340, 160, 30);

        A10.setBackground(new java.awt.Color(204, 204, 204));
        A10.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        A10.setText("DIAMOND ");
        A10.setOpaque(true);
        jPanel1.add(A10);
        A10.setBounds(550, 340, 160, 30);

        A11.setBackground(new java.awt.Color(204, 204, 204));
        A11.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        A11.setText("TIARA");
        A11.setOpaque(true);
        jPanel1.add(A11);
        A11.setBounds(610, 340, 110, 30);

        A12.setBackground(new java.awt.Color(204, 204, 204));
        A12.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        A12.setText("RING");
        A12.setOpaque(true);
        jPanel1.add(A12);
        A12.setBounds(670, 340, 100, 30);

        A25.setBackground(new java.awt.Color(204, 204, 204));
        A25.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        A25.setText("MIRROR");
        A25.setOpaque(true);
        jPanel1.add(A25);
        A25.setBounds(520, 70, 140, 30);

        A15.setBackground(new java.awt.Color(204, 204, 204));
        A15.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        A15.setText("BROOCH");
        A15.setOpaque(true);
        jPanel1.add(A15);
        A15.setBounds(650, 270, 140, 30);

        A16.setBackground(new java.awt.Color(204, 204, 204));
        A16.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        A16.setText("BRACELET");
        A16.setOpaque(true);
        jPanel1.add(A16);
        A16.setBounds(680, 180, 140, 30);

        A23.setBackground(new java.awt.Color(204, 204, 204));
        A23.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        A23.setText("BOX");
        A23.setOpaque(true);
        jPanel1.add(A23);
        A23.setBounds(290, 160, 70, 30);

        A22.setBackground(new java.awt.Color(204, 204, 204));
        A22.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        A22.setText("LINK");
        A22.setOpaque(true);
        jPanel1.add(A22);
        A22.setBounds(350, 160, 80, 30);

        A21.setBackground(new java.awt.Color(204, 204, 204));
        A21.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        A21.setText("RING");
        A21.setOpaque(true);
        jPanel1.add(A21);
        A21.setBounds(400, 150, 90, 30);

        A20.setBackground(new java.awt.Color(204, 204, 204));
        A20.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        A20.setText("GOLD EARRINGS ");
        A20.setOpaque(true);
        jPanel1.add(A20);
        A20.setBounds(400, 150, 230, 30);

        A19.setBackground(new java.awt.Color(204, 204, 204));
        A19.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        A19.setText("NECKLACE");
        A19.setOpaque(true);
        jPanel1.add(A19);
        A19.setBounds(450, 150, 180, 30);

        A18.setBackground(new java.awt.Color(204, 204, 204));
        A18.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        A18.setText("TWEEZERS ");
        A18.setOpaque(true);
        jPanel1.add(A18);
        A18.setBounds(490, 150, 150, 30);

        A17.setBackground(new java.awt.Color(204, 204, 204));
        A17.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        A17.setText("CHAIN");
        A17.setOpaque(true);
        jPanel1.add(A17);
        A17.setBounds(570, 160, 100, 30);

        A24.setBackground(new java.awt.Color(204, 204, 204));
        A24.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        A24.setText("BAG");
        A24.setOpaque(true);
        jPanel1.add(A24);
        A24.setBounds(260, 80, 60, 30);

        jSalir.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jSalir.setForeground(new java.awt.Color(240, 240, 240));
        jSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/45.png"))); // NOI18N
        jSalir.setText("<");
        jSalir.setBorder(null);
        jSalir.setBorderPainted(false);
        jSalir.setContentAreaFilled(false);
        jSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jSalir.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/35.png"))); // NOI18N
        jSalir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/40.png"))); // NOI18N
        jSalir.setVerifyInputWhenFocusTarget(false);
        jSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSalirActionPerformed(evt);
            }
        });
        jPanel1.add(jSalir);
        jSalir.setBounds(20, 20, 31, 31);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondos/fjoyeria.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 890, 471);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 890, 470);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
 AudioClip sonido;
        sonido= java.applet.Applet.newAudioClip(getClass().getResource("/audio/cash register.wav"));
        sonido.play();        // TODO add your handling code here:
        A1.setVisible(true);
        A2.setVisible(false);
        A3.setVisible(false);
        A4.setVisible(false);
        A5.setVisible(false);
        A6.setVisible(false);
        A7.setVisible(false);
        A8.setVisible(false);
        A9.setVisible(false);
        A10.setVisible(false);
        A11.setVisible(false);
        A12.setVisible(false);
        A13.setVisible(false);
        A14.setVisible(false);
        A15.setVisible(false);
        A16.setVisible(false);
        A17.setVisible(false);
        A18.setVisible(false);
        A19.setVisible(false);
        A20.setVisible(false);
        A21.setVisible(false);
        A22.setVisible(false);
        A23.setVisible(false);
        A24.setVisible(false);
        A25.setVisible(false);
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
 AudioClip sonido;
        sonido= java.applet.Applet.newAudioClip(getClass().getResource("/audio/plant.wav"));
        sonido.play();        // TODO add your handling code here:
        A1.setVisible(false);
        A2.setVisible(true);
        A3.setVisible(false);
        A4.setVisible(false);
        A5.setVisible(false);
        A6.setVisible(false);
        A7.setVisible(false);
        A8.setVisible(false);
        A9.setVisible(false);
        A10.setVisible(false);
        A11.setVisible(false);
        A12.setVisible(false);
        A13.setVisible(false);
        A14.setVisible(false);
        A15.setVisible(false);
        A16.setVisible(false);
        A17.setVisible(false);
        A18.setVisible(false);
        A19.setVisible(false);
        A20.setVisible(false);
        A21.setVisible(false);
        A22.setVisible(false);
        A23.setVisible(false);
        A24.setVisible(false);
        A25.setVisible(false);
    }//GEN-LAST:event_jButton24ActionPerformed

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
 AudioClip sonido;
        sonido= java.applet.Applet.newAudioClip(getClass().getResource("/audio/crown.wav"));
        sonido.play();        // TODO add your handling code here:
        A1.setVisible(false);
        A2.setVisible(false);
        A3.setVisible(false);
        A4.setVisible(true);
        A5.setVisible(false);
        A6.setVisible(false);
        A7.setVisible(false);
        A8.setVisible(false);
        A9.setVisible(false);
        A10.setVisible(false);
        A11.setVisible(false);
        A12.setVisible(false);
        A13.setVisible(false);
        A14.setVisible(false);
        A15.setVisible(false);
        A16.setVisible(false);
        A17.setVisible(false);
        A18.setVisible(false);
        A19.setVisible(false);
        A20.setVisible(false);
        A21.setVisible(false);
        A22.setVisible(false);
        A23.setVisible(false);
        A24.setVisible(false);
        A25.setVisible(false);
    }//GEN-LAST:event_jButton25ActionPerformed

    private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton26ActionPerformed
 AudioClip sonido;
        sonido= java.applet.Applet.newAudioClip(getClass().getResource("/audio/clock.wav"));
        sonido.play();        // TODO add your handling code here:
        A1.setVisible(false);
        A2.setVisible(false);
        A3.setVisible(false);
        A4.setVisible(false);
        A5.setVisible(true);
        A6.setVisible(false);
        A7.setVisible(false);
        A8.setVisible(false);
        A9.setVisible(false);
        A10.setVisible(false);
        A11.setVisible(false);
        A12.setVisible(false);
        A13.setVisible(false);
        A14.setVisible(false);
        A15.setVisible(false);
        A16.setVisible(false);
        A17.setVisible(false);
        A18.setVisible(false);
        A19.setVisible(false);
        A20.setVisible(false);
        A21.setVisible(false);
        A22.setVisible(false);
        A23.setVisible(false);
        A24.setVisible(false);
        A25.setVisible(false);
    }//GEN-LAST:event_jButton26ActionPerformed

    private void jButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton27ActionPerformed
    AudioClip sonido;
        sonido= java.applet.Applet.newAudioClip(getClass().getResource("/audio/earrings.wav"));
        sonido.play();     // TODO add your handling code here:
        A1.setVisible(false);
        A2.setVisible(false);
        A3.setVisible(false);
        A4.setVisible(false);
        A5.setVisible(false);
        A6.setVisible(true);
        A7.setVisible(false);
        A8.setVisible(false);
        A9.setVisible(false);
        A10.setVisible(false);
        A11.setVisible(false);
        A12.setVisible(false);
        A13.setVisible(false);
        A14.setVisible(false);
        A15.setVisible(false);
        A16.setVisible(false);
        A17.setVisible(false);
        A18.setVisible(false);
        A19.setVisible(false);
        A20.setVisible(false);
        A21.setVisible(false);
        A22.setVisible(false);
        A23.setVisible(false);
        A24.setVisible(false);
        A25.setVisible(false);
    }//GEN-LAST:event_jButton27ActionPerformed

    private void jButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton28ActionPerformed
  AudioClip sonido;
        sonido= java.applet.Applet.newAudioClip(getClass().getResource("/audio/box.wav"));
        sonido.play();       // TODO add your handling code here:
        A1.setVisible(false);
        A2.setVisible(false);
        A3.setVisible(false);
        A4.setVisible(false);
        A5.setVisible(false);
        A6.setVisible(false);
        A7.setVisible(false);
        A8.setVisible(false);
        A9.setVisible(false);
        A10.setVisible(false);
        A11.setVisible(false);
        A12.setVisible(false);
        A13.setVisible(false);
        A14.setVisible(false);
        A15.setVisible(false);
        A16.setVisible(false);
        A17.setVisible(false);
        A18.setVisible(false);
        A19.setVisible(false);
        A20.setVisible(false);
        A21.setVisible(false);
        A22.setVisible(false);
        A23.setVisible(true);
        A24.setVisible(false);
        A25.setVisible(false);
    }//GEN-LAST:event_jButton28ActionPerformed

    private void jButton29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton29ActionPerformed
 AudioClip sonido;
        sonido= java.applet.Applet.newAudioClip(getClass().getResource("/audio/necklace.wav"));
        sonido.play();        // TODO add your handling code here:
        A1.setVisible(false);
        A2.setVisible(false);
        A3.setVisible(false);
        A4.setVisible(false);
        A5.setVisible(false);
        A6.setVisible(false);
        A7.setVisible(true);
        A8.setVisible(false);
        A9.setVisible(false);
        A10.setVisible(false);
        A11.setVisible(false);
        A12.setVisible(false);
        A13.setVisible(false);
        A14.setVisible(false);
        A15.setVisible(false);
        A16.setVisible(false);
        A17.setVisible(false);
        A18.setVisible(false);
        A19.setVisible(false);
        A20.setVisible(false);
        A21.setVisible(false);
        A22.setVisible(false);
        A23.setVisible(false);
        A24.setVisible(false);
        A25.setVisible(false);
    }//GEN-LAST:event_jButton29ActionPerformed

    private void jButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton30ActionPerformed
 AudioClip sonido;
        sonido= java.applet.Applet.newAudioClip(getClass().getResource("/audio/slopes.wav"));
        sonido.play();        // TODO add your handling code here:
        A1.setVisible(false);
        A2.setVisible(false);
        A3.setVisible(false);
        A4.setVisible(false);
        A5.setVisible(false);
        A6.setVisible(false);
        A7.setVisible(false);
        A8.setVisible(true);
        A9.setVisible(false);
        A10.setVisible(false);
        A11.setVisible(false);
        A12.setVisible(false);
        A13.setVisible(false);
        A14.setVisible(false);
        A15.setVisible(false);
        A16.setVisible(false);
        A17.setVisible(false);
        A18.setVisible(false);
        A19.setVisible(false);
        A20.setVisible(false);
        A21.setVisible(false);
        A22.setVisible(false);
        A23.setVisible(false);
        A24.setVisible(false);
        A25.setVisible(false);
    }//GEN-LAST:event_jButton30ActionPerformed

    private void jButton31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton31ActionPerformed
 AudioClip sonido;
        sonido= java.applet.Applet.newAudioClip(getClass().getResource("/audio/bracelet.wav"));
        sonido.play();        // TODO add your handling code here:
        A1.setVisible(false);
        A2.setVisible(false);
        A3.setVisible(false);
        A4.setVisible(false);
        A5.setVisible(false);
        A6.setVisible(false);
        A7.setVisible(false);
        A8.setVisible(false);
        A9.setVisible(true);
        A10.setVisible(false);
        A11.setVisible(false);
        A12.setVisible(false);
        A13.setVisible(false);
        A14.setVisible(false);
        A15.setVisible(false);
        A16.setVisible(false);
        A17.setVisible(false);
        A18.setVisible(false);
        A19.setVisible(false);
        A20.setVisible(false);
        A21.setVisible(false);
        A22.setVisible(false);
        A23.setVisible(false);
        A24.setVisible(false);
        A25.setVisible(false);
    }//GEN-LAST:event_jButton31ActionPerformed

    private void jButton32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton32ActionPerformed
 AudioClip sonido;
        sonido= java.applet.Applet.newAudioClip(getClass().getResource("/audio/diamond.wav"));
        sonido.play();        // TODO add your handling code here:
        A1.setVisible(false);
        A2.setVisible(false);
        A3.setVisible(false);
        A4.setVisible(false);
        A5.setVisible(false);
        A6.setVisible(false);
        A7.setVisible(false);
        A8.setVisible(false);
        A9.setVisible(false);
        A10.setVisible(true);
        A11.setVisible(false);
        A12.setVisible(false);
        A13.setVisible(false);
        A14.setVisible(false);
        A15.setVisible(false);
        A16.setVisible(false);
        A17.setVisible(false);
        A18.setVisible(false);
        A19.setVisible(false);
        A20.setVisible(false);
        A21.setVisible(false);
        A22.setVisible(false);
        A23.setVisible(false);
        A24.setVisible(false);
        A25.setVisible(false);
    }//GEN-LAST:event_jButton32ActionPerformed

    private void jButton33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton33ActionPerformed
 AudioClip sonido;
        sonido= java.applet.Applet.newAudioClip(getClass().getResource("/audio/tiara.wav"));
        sonido.play();        // TODO add your handling code here:
        A1.setVisible(false);
        A2.setVisible(false);
        A3.setVisible(false);
        A4.setVisible(false);
        A5.setVisible(false);
        A6.setVisible(false);
        A7.setVisible(false);
        A8.setVisible(false);
        A9.setVisible(false);
        A10.setVisible(false);
        A11.setVisible(true);
        A12.setVisible(false);
        A13.setVisible(false);
        A14.setVisible(false);
        A15.setVisible(false);
        A16.setVisible(false);
        A17.setVisible(false);
        A18.setVisible(false);
        A19.setVisible(false);
        A20.setVisible(false);
        A21.setVisible(false);
        A22.setVisible(false);
        A23.setVisible(false);
        A24.setVisible(false);
        A25.setVisible(false);
    }//GEN-LAST:event_jButton33ActionPerformed

    private void jButton34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton34ActionPerformed
 AudioClip sonido;
        sonido= java.applet.Applet.newAudioClip(getClass().getResource("/audio/ring.wav"));
        sonido.play();        // TODO add your handling code here:
        A1.setVisible(false);
        A2.setVisible(false);
        A3.setVisible(false);
        A4.setVisible(false);
        A5.setVisible(false);
        A6.setVisible(false);
        A7.setVisible(false);
        A8.setVisible(false);
        A9.setVisible(false);
        A10.setVisible(false);
        A11.setVisible(false);
        A12.setVisible(true);
        A13.setVisible(false);
        A14.setVisible(false);
        A15.setVisible(false);
        A16.setVisible(false);
        A17.setVisible(false);
        A18.setVisible(false);
        A19.setVisible(false);
        A20.setVisible(false);
        A21.setVisible(false);
        A22.setVisible(false);
        A23.setVisible(false);
        A24.setVisible(false);
        A25.setVisible(false);
    }//GEN-LAST:event_jButton34ActionPerformed

    private void jButton35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton35ActionPerformed
 AudioClip sonido;
        sonido= java.applet.Applet.newAudioClip(getClass().getResource("/audio/brooch.wav"));
        sonido.play();        // TODO add your handling code here:
        A1.setVisible(false);
        A2.setVisible(false);
        A3.setVisible(false);
        A4.setVisible(false);
        A5.setVisible(false);
        A6.setVisible(false);
        A7.setVisible(false);
        A8.setVisible(false);
        A9.setVisible(false);
        A10.setVisible(false);
        A11.setVisible(false);
        A12.setVisible(false);
        A13.setVisible(false);
        A14.setVisible(false);
        A15.setVisible(true);
        A16.setVisible(false);
        A17.setVisible(false);
        A18.setVisible(false);
        A19.setVisible(false);
        A20.setVisible(false);
        A21.setVisible(false);
        A22.setVisible(false);
        A23.setVisible(false);
        A24.setVisible(false);
        A25.setVisible(false);
    }//GEN-LAST:event_jButton35ActionPerformed

    private void jButton36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton36ActionPerformed
 AudioClip sonido;
        sonido= java.applet.Applet.newAudioClip(getClass().getResource("/audio/bracelet.wav"));
        sonido.play();        // TODO add your handling code here:
        A1.setVisible(false);
        A2.setVisible(false);
        A3.setVisible(false);
        A4.setVisible(false);
        A5.setVisible(false);
        A6.setVisible(false);
        A7.setVisible(false);
        A8.setVisible(false);
        A9.setVisible(false);
        A10.setVisible(false);
        A11.setVisible(false);
        A12.setVisible(false);
        A13.setVisible(false);
        A14.setVisible(false);
        A15.setVisible(false);
        A16.setVisible(true);
        A17.setVisible(false);
        A18.setVisible(false);
        A19.setVisible(false);
        A20.setVisible(false);
        A21.setVisible(false);
        A22.setVisible(false);
        A23.setVisible(false);
        A24.setVisible(false);
        A25.setVisible(false);
    }//GEN-LAST:event_jButton36ActionPerformed

    private void jButton37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton37ActionPerformed
 AudioClip sonido;
        sonido= java.applet.Applet.newAudioClip(getClass().getResource("/audio/chain.wav"));
        sonido.play();        // TODO add your handling code here:
        A1.setVisible(false);
        A2.setVisible(false);
        A3.setVisible(false);
        A4.setVisible(false);
        A5.setVisible(false);
        A6.setVisible(false);
        A7.setVisible(false);
        A8.setVisible(false);
        A9.setVisible(false);
        A10.setVisible(false);
        A11.setVisible(false);
        A12.setVisible(false);
        A13.setVisible(false);
        A14.setVisible(false);
        A15.setVisible(false);
        A16.setVisible(false);
        A17.setVisible(true);
        A18.setVisible(false);
        A19.setVisible(false);
        A20.setVisible(false);
        A21.setVisible(false);
        A22.setVisible(false);
        A23.setVisible(false);
        A24.setVisible(false);
        A25.setVisible(false);
    }//GEN-LAST:event_jButton37ActionPerformed

    private void jButton38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton38ActionPerformed
 AudioClip sonido;
        sonido= java.applet.Applet.newAudioClip(getClass().getResource("/audio/tweezers.wav"));
        sonido.play();        // TODO add your handling code here:
        A1.setVisible(false);
        A2.setVisible(false);
        A3.setVisible(false);
        A4.setVisible(false);
        A5.setVisible(false);
        A6.setVisible(false);
        A7.setVisible(false);
        A8.setVisible(false);
        A9.setVisible(false);
        A10.setVisible(false);
        A11.setVisible(false);
        A12.setVisible(false);
        A13.setVisible(false);
        A14.setVisible(false);
        A15.setVisible(false);
        A16.setVisible(false);
        A17.setVisible(false);
        A18.setVisible(true);
        A19.setVisible(false);
        A20.setVisible(false);
        A21.setVisible(false);
        A22.setVisible(false);
        A23.setVisible(false);
        A24.setVisible(false);
        A25.setVisible(false);
    }//GEN-LAST:event_jButton38ActionPerformed

    private void jButton39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton39ActionPerformed
 AudioClip sonido;
        sonido= java.applet.Applet.newAudioClip(getClass().getResource("/audio/necklace.wav"));
        sonido.play();        // TODO add your handling code here:
        A1.setVisible(false);
        A2.setVisible(false);
        A3.setVisible(false);
        A4.setVisible(false);
        A5.setVisible(false);
        A6.setVisible(false);
        A7.setVisible(false);
        A8.setVisible(false);
        A9.setVisible(false);
        A10.setVisible(false);
        A11.setVisible(false);
        A12.setVisible(false);
        A13.setVisible(false);
        A14.setVisible(false);
        A15.setVisible(false);
        A16.setVisible(false);
        A17.setVisible(false);
        A18.setVisible(false);
        A19.setVisible(true);
        A20.setVisible(false);
        A21.setVisible(false);
        A22.setVisible(false);
        A23.setVisible(false);
        A24.setVisible(false);
        A25.setVisible(false);
    }//GEN-LAST:event_jButton39ActionPerformed

    private void jButton40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton40ActionPerformed
 AudioClip sonido;
        sonido= java.applet.Applet.newAudioClip(getClass().getResource("/audio/gold earrings.wav"));
        sonido.play();        // TODO add your handling code here:
        A1.setVisible(false);
        A2.setVisible(false);
        A3.setVisible(false);
        A4.setVisible(false);
        A5.setVisible(false);
        A6.setVisible(false);
        A7.setVisible(false);
        A8.setVisible(false);
        A9.setVisible(false);
        A10.setVisible(false);
        A11.setVisible(false);
        A12.setVisible(false);
        A13.setVisible(false);
        A14.setVisible(false);
        A15.setVisible(false);
        A16.setVisible(false);
        A17.setVisible(false);
        A18.setVisible(false);
        A19.setVisible(false);
        A20.setVisible(true);
        A21.setVisible(false);
        A22.setVisible(false);
        A23.setVisible(false);
        A24.setVisible(false);
        A25.setVisible(false);
    }//GEN-LAST:event_jButton40ActionPerformed

    private void jButton41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton41ActionPerformed
 AudioClip sonido;
        sonido= java.applet.Applet.newAudioClip(getClass().getResource("/audio/ring.wav"));
        sonido.play();        // TODO add your handling code here:
        A1.setVisible(false);
        A2.setVisible(false);
        A3.setVisible(false);
        A4.setVisible(false);
        A5.setVisible(false);
        A6.setVisible(false);
        A7.setVisible(false);
        A8.setVisible(false);
        A9.setVisible(false);
        A10.setVisible(false);
        A11.setVisible(false);
        A12.setVisible(false);
        A13.setVisible(false);
        A14.setVisible(false);
        A15.setVisible(false);
        A16.setVisible(false);
        A17.setVisible(false);
        A18.setVisible(false);
        A19.setVisible(false);
        A20.setVisible(false);
        A21.setVisible(true);
        A22.setVisible(false);
        A23.setVisible(false);
        A24.setVisible(false);
        A25.setVisible(false);
    }//GEN-LAST:event_jButton41ActionPerformed

    private void jButton42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton42ActionPerformed
       AudioClip sonido;
        sonido= java.applet.Applet.newAudioClip(getClass().getResource("/audio/link.wav"));
        sonido.play();  // TODO add your handling code here:
        A1.setVisible(false);
        A2.setVisible(false);
        A3.setVisible(false);
        A4.setVisible(false);
        A5.setVisible(false);
        A6.setVisible(false);
        A7.setVisible(false);
        A8.setVisible(false);
        A9.setVisible(false);
        A10.setVisible(false);
        A11.setVisible(false);
        A12.setVisible(false);
        A13.setVisible(false);
        A14.setVisible(false);
        A15.setVisible(false);
        A16.setVisible(false);
        A17.setVisible(false);
        A18.setVisible(false);
        A19.setVisible(false);
        A20.setVisible(false);
        A21.setVisible(false);
        A22.setVisible(true);
        A23.setVisible(false);
        A24.setVisible(false);
        A25.setVisible(false);
    }//GEN-LAST:event_jButton42ActionPerformed

    private void jButton43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton43ActionPerformed
 AudioClip sonido;
        sonido= java.applet.Applet.newAudioClip(getClass().getResource("/audio/bag.wav"));
        sonido.play();        // TODO add your handling code here:
        A1.setVisible(false);
        A2.setVisible(false);
        A3.setVisible(false);
        A4.setVisible(false);
        A5.setVisible(false);
        A6.setVisible(false);
        A7.setVisible(false);
        A8.setVisible(false);
        A9.setVisible(false);
        A10.setVisible(false);
        A11.setVisible(false);
        A12.setVisible(false);
        A13.setVisible(false);
        A14.setVisible(false);
        A15.setVisible(false);
        A16.setVisible(false);
        A17.setVisible(false);
        A18.setVisible(false);
        A19.setVisible(false);
        A20.setVisible(false);
        A21.setVisible(false);
        A22.setVisible(false);
        A23.setVisible(false);
        A24.setVisible(true);
        A25.setVisible(false);
    }//GEN-LAST:event_jButton43ActionPerformed

    private void jButton44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton44ActionPerformed
 AudioClip sonido;
        sonido= java.applet.Applet.newAudioClip(getClass().getResource("/audio/mirror.wav"));
        sonido.play();        // TODO add your handling code here:
        A1.setVisible(false);
        A2.setVisible(false);
        A3.setVisible(false);
        A4.setVisible(false);
        A5.setVisible(false);
        A6.setVisible(false);
        A7.setVisible(false);
        A8.setVisible(false);
        A9.setVisible(false);
        A10.setVisible(false);
        A11.setVisible(false);
        A12.setVisible(false);
        A13.setVisible(false);
        A14.setVisible(false);
        A15.setVisible(false);
        A16.setVisible(false);
        A17.setVisible(false);
        A18.setVisible(false);
        A19.setVisible(false);
        A20.setVisible(false);
        A21.setVisible(false);
        A22.setVisible(false);
        A23.setVisible(false);
        A24.setVisible(false);
        A25.setVisible(true);
    }//GEN-LAST:event_jButton44ActionPerformed

    private void jButton45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton45ActionPerformed
 AudioClip sonido;
        sonido= java.applet.Applet.newAudioClip(getClass().getResource("/audio/table.wav"));
        sonido.play();        // TODO add your handling code here:
        A1.setVisible(false);
        A2.setVisible(false);
        A3.setVisible(true);
        A4.setVisible(false);
        A5.setVisible(false);
        A6.setVisible(false);
        A7.setVisible(false);
        A8.setVisible(false);
        A9.setVisible(false);
        A10.setVisible(false);
        A11.setVisible(false);
        A12.setVisible(false);
        A13.setVisible(false);
        A14.setVisible(false);
        A15.setVisible(false);
        A16.setVisible(false);
        A17.setVisible(false);
        A18.setVisible(false);
        A19.setVisible(false);
        A20.setVisible(false);
        A21.setVisible(false);
        A22.setVisible(false);
        A23.setVisible(false);
        A24.setVisible(false);
        A25.setVisible(false);
    }//GEN-LAST:event_jButton45ActionPerformed

    private void jButton46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton46ActionPerformed
 AudioClip sonido;
        sonido= java.applet.Applet.newAudioClip(getClass().getResource("/audio/logo.wav"));
        sonido.play();        // TODO add your handling code here:
        A1.setVisible(false);
        A2.setVisible(false);
        A3.setVisible(false);
        A4.setVisible(false);
        A5.setVisible(false);
        A6.setVisible(false);
        A7.setVisible(false);
        A8.setVisible(false);
        A9.setVisible(false);
        A10.setVisible(false);
        A11.setVisible(false);
        A12.setVisible(false);
        A13.setVisible(true);
        A14.setVisible(false);
        A15.setVisible(false);
        A16.setVisible(false);
        A17.setVisible(false);
        A18.setVisible(false);
        A19.setVisible(false);
        A20.setVisible(false);
        A21.setVisible(false);
        A22.setVisible(false);
        A23.setVisible(false);
        A24.setVisible(false);
        A25.setVisible(false);
    }//GEN-LAST:event_jButton46ActionPerformed

    private void jButton47ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton47ActionPerformed
 AudioClip sonido;
        sonido= java.applet.Applet.newAudioClip(getClass().getResource("/audio/saleswoman.wav"));
        sonido.play();        // TODO add your handling code here:
        A1.setVisible(false);
        A2.setVisible(false);
        A3.setVisible(false);
        A4.setVisible(false);
        A5.setVisible(false);
        A6.setVisible(false);
        A7.setVisible(false);
        A8.setVisible(false);
        A9.setVisible(false);
        A10.setVisible(false);
        A11.setVisible(false);
        A12.setVisible(false);
        A13.setVisible(false);
        A14.setVisible(true);
        A15.setVisible(false);
        A16.setVisible(false);
        A17.setVisible(false);
        A18.setVisible(false);
        A19.setVisible(false);
        A20.setVisible(false);
        A21.setVisible(false);
        A22.setVisible(false);
        A23.setVisible(false);
        A24.setVisible(false);
        A25.setVisible(false);
    }//GEN-LAST:event_jButton47ActionPerformed

    private void jSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSalirActionPerformed
        new Menu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Joyeria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Joyeria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Joyeria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Joyeria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Joyeria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel A1;
    private javax.swing.JLabel A10;
    private javax.swing.JLabel A11;
    private javax.swing.JLabel A12;
    private javax.swing.JLabel A13;
    private javax.swing.JLabel A14;
    private javax.swing.JLabel A15;
    private javax.swing.JLabel A16;
    private javax.swing.JLabel A17;
    private javax.swing.JLabel A18;
    private javax.swing.JLabel A19;
    private javax.swing.JLabel A2;
    private javax.swing.JLabel A20;
    private javax.swing.JLabel A21;
    private javax.swing.JLabel A22;
    private javax.swing.JLabel A23;
    private javax.swing.JLabel A24;
    private javax.swing.JLabel A25;
    private javax.swing.JLabel A3;
    private javax.swing.JLabel A4;
    private javax.swing.JLabel A5;
    private javax.swing.JLabel A6;
    private javax.swing.JLabel A7;
    private javax.swing.JLabel A8;
    private javax.swing.JLabel A9;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton42;
    private javax.swing.JButton jButton43;
    private javax.swing.JButton jButton44;
    private javax.swing.JButton jButton45;
    private javax.swing.JButton jButton46;
    private javax.swing.JButton jButton47;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jSalir;
    // End of variables declaration//GEN-END:variables
}
