package Modulos;

import java.applet.AudioClip;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Home1
 */
public class Libreria extends javax.swing.JFrame {

    /**
     * Creates new form libreria
     */
    public Libreria() {
        
        initComponents();
        this.setSize(1024,482);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        l1.setVisible(false);
        l2.setVisible(false);
        l3.setVisible(false);
        l4.setVisible(false);
        l5.setVisible(false);
        l6.setVisible(false);
        l7.setVisible(false);
        l8.setVisible(false);
        l9.setVisible(false);
        l10.setVisible(false);
        l11.setVisible(false);
        l12.setVisible(false);
        l13.setVisible(false);
        l14.setVisible(false);
        l15.setVisible(false);
        l16.setVisible(false);
        l17.setVisible(false);
        l18.setVisible(false);
        l19.setVisible(false);
        l20.setVisible(false);
        l21.setVisible(false);
        l22.setVisible(false);
        l23.setVisible(false);
        l24.setVisible(false);
        l25.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        q16 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jButton40 = new javax.swing.JButton();
        jButton41 = new javax.swing.JButton();
        jButton42 = new javax.swing.JButton();
        l1 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        l4 = new javax.swing.JLabel();
        l5 = new javax.swing.JLabel();
        l6 = new javax.swing.JLabel();
        l7 = new javax.swing.JLabel();
        l8 = new javax.swing.JLabel();
        l9 = new javax.swing.JLabel();
        l16 = new javax.swing.JLabel();
        l15 = new javax.swing.JLabel();
        l11 = new javax.swing.JLabel();
        l17 = new javax.swing.JLabel();
        l18 = new javax.swing.JLabel();
        l22 = new javax.swing.JLabel();
        l23 = new javax.swing.JLabel();
        l24 = new javax.swing.JLabel();
        l25 = new javax.swing.JLabel();
        l21 = new javax.swing.JLabel();
        l13 = new javax.swing.JLabel();
        l14 = new javax.swing.JLabel();
        l12 = new javax.swing.JLabel();
        l19 = new javax.swing.JLabel();
        l20 = new javax.swing.JLabel();
        l10 = new javax.swing.JLabel();
        jSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton18.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jButton18.setForeground(new java.awt.Color(240, 240, 240));
        jButton18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/25.png"))); // NOI18N
        jButton18.setText("19");
        jButton18.setBorder(null);
        jButton18.setBorderPainted(false);
        jButton18.setContentAreaFilled(false);
        jButton18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton18.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton18.setVerifyInputWhenFocusTarget(false);
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton18);
        jButton18.setBounds(680, 170, 40, 40);

        jButton19.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jButton19.setForeground(new java.awt.Color(240, 240, 240));
        jButton19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/25.png"))); // NOI18N
        jButton19.setText("24");
        jButton19.setBorder(null);
        jButton19.setBorderPainted(false);
        jButton19.setContentAreaFilled(false);
        jButton19.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton19.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton19.setVerifyInputWhenFocusTarget(false);
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton19);
        jButton19.setBounds(890, 240, 40, 40);

        jButton20.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jButton20.setForeground(new java.awt.Color(240, 240, 240));
        jButton20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/25.png"))); // NOI18N
        jButton20.setText("21");
        jButton20.setBorder(null);
        jButton20.setBorderPainted(false);
        jButton20.setContentAreaFilled(false);
        jButton20.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton20.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton20.setVerifyInputWhenFocusTarget(false);
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton20);
        jButton20.setBounds(700, 290, 40, 40);

        jButton21.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jButton21.setForeground(new java.awt.Color(240, 240, 240));
        jButton21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/25.png"))); // NOI18N
        jButton21.setText("15");
        jButton21.setBorder(null);
        jButton21.setBorderPainted(false);
        jButton21.setContentAreaFilled(false);
        jButton21.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton21.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton21.setVerifyInputWhenFocusTarget(false);
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton21);
        jButton21.setBounds(750, 60, 40, 40);

        jButton22.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jButton22.setForeground(new java.awt.Color(240, 240, 240));
        jButton22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/25.png"))); // NOI18N
        jButton22.setText("9");
        jButton22.setBorder(null);
        jButton22.setBorderPainted(false);
        jButton22.setContentAreaFilled(false);
        jButton22.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton22.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton22.setVerifyInputWhenFocusTarget(false);
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton22);
        jButton22.setBounds(600, 10, 40, 40);

        jButton23.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jButton23.setForeground(new java.awt.Color(240, 240, 240));
        jButton23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/25.png"))); // NOI18N
        jButton23.setText("14");
        jButton23.setBorder(null);
        jButton23.setBorderPainted(false);
        jButton23.setContentAreaFilled(false);
        jButton23.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton23.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton23.setVerifyInputWhenFocusTarget(false);
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton23);
        jButton23.setBounds(630, 330, 40, 40);

        jButton24.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jButton24.setForeground(new java.awt.Color(240, 240, 240));
        jButton24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/25.png"))); // NOI18N
        jButton24.setText("25");
        jButton24.setBorder(null);
        jButton24.setBorderPainted(false);
        jButton24.setContentAreaFilled(false);
        jButton24.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton24.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton24.setVerifyInputWhenFocusTarget(false);
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton24);
        jButton24.setBounds(820, 350, 40, 40);

        jButton25.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jButton25.setForeground(new java.awt.Color(240, 240, 240));
        jButton25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/25.png"))); // NOI18N
        jButton25.setText("23");
        jButton25.setBorder(null);
        jButton25.setBorderPainted(false);
        jButton25.setContentAreaFilled(false);
        jButton25.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton25.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton25.setVerifyInputWhenFocusTarget(false);
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton25);
        jButton25.setBounds(940, 180, 40, 40);

        q16.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        q16.setForeground(new java.awt.Color(240, 240, 240));
        q16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/25.png"))); // NOI18N
        q16.setText("16");
        q16.setBorder(null);
        q16.setBorderPainted(false);
        q16.setContentAreaFilled(false);
        q16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        q16.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        q16.setVerifyInputWhenFocusTarget(false);
        q16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q16ActionPerformed(evt);
            }
        });
        getContentPane().add(q16);
        q16.setBounds(830, 10, 40, 40);

        jButton27.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jButton27.setForeground(new java.awt.Color(240, 240, 240));
        jButton27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/25.png"))); // NOI18N
        jButton27.setText("2");
        jButton27.setBorder(null);
        jButton27.setBorderPainted(false);
        jButton27.setContentAreaFilled(false);
        jButton27.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton27.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton27.setVerifyInputWhenFocusTarget(false);
        jButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton27ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton27);
        jButton27.setBounds(110, 220, 40, 40);

        jButton28.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jButton28.setForeground(new java.awt.Color(240, 240, 240));
        jButton28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/25.png"))); // NOI18N
        jButton28.setText("18");
        jButton28.setBorder(null);
        jButton28.setBorderPainted(false);
        jButton28.setContentAreaFilled(false);
        jButton28.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton28.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton28.setVerifyInputWhenFocusTarget(false);
        jButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton28ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton28);
        jButton28.setBounds(780, 140, 40, 40);

        jButton29.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jButton29.setForeground(new java.awt.Color(240, 240, 240));
        jButton29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/25.png"))); // NOI18N
        jButton29.setText("5");
        jButton29.setBorder(null);
        jButton29.setBorderPainted(false);
        jButton29.setContentAreaFilled(false);
        jButton29.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton29.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton29.setVerifyInputWhenFocusTarget(false);
        jButton29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton29ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton29);
        jButton29.setBounds(270, 320, 40, 40);

        jButton30.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jButton30.setForeground(new java.awt.Color(240, 240, 240));
        jButton30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/25.png"))); // NOI18N
        jButton30.setText("20");
        jButton30.setBorder(null);
        jButton30.setBorderPainted(false);
        jButton30.setContentAreaFilled(false);
        jButton30.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton30.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton30.setVerifyInputWhenFocusTarget(false);
        jButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton30ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton30);
        jButton30.setBounds(710, 220, 40, 40);

        jButton31.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jButton31.setForeground(new java.awt.Color(240, 240, 240));
        jButton31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/25.png"))); // NOI18N
        jButton31.setText("1");
        jButton31.setBorder(null);
        jButton31.setBorderPainted(false);
        jButton31.setContentAreaFilled(false);
        jButton31.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton31.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton31.setVerifyInputWhenFocusTarget(false);
        jButton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton31ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton31);
        jButton31.setBounds(110, 0, 40, 40);

        jButton32.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jButton32.setForeground(new java.awt.Color(240, 240, 240));
        jButton32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/25.png"))); // NOI18N
        jButton32.setText("4");
        jButton32.setBorder(null);
        jButton32.setBorderPainted(false);
        jButton32.setContentAreaFilled(false);
        jButton32.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton32.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton32.setVerifyInputWhenFocusTarget(false);
        jButton32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton32ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton32);
        jButton32.setBounds(200, 340, 40, 40);

        jButton33.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jButton33.setForeground(new java.awt.Color(240, 240, 240));
        jButton33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/25.png"))); // NOI18N
        jButton33.setText("12");
        jButton33.setBorder(null);
        jButton33.setBorderPainted(false);
        jButton33.setContentAreaFilled(false);
        jButton33.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton33.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton33.setVerifyInputWhenFocusTarget(false);
        jButton33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton33ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton33);
        jButton33.setBounds(630, 190, 40, 40);

        jButton34.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jButton34.setForeground(new java.awt.Color(240, 240, 240));
        jButton34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/25.png"))); // NOI18N
        jButton34.setText("6");
        jButton34.setBorder(null);
        jButton34.setBorderPainted(false);
        jButton34.setContentAreaFilled(false);
        jButton34.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton34.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton34.setVerifyInputWhenFocusTarget(false);
        jButton34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton34ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton34);
        jButton34.setBounds(420, 300, 40, 40);

        jButton35.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jButton35.setForeground(new java.awt.Color(240, 240, 240));
        jButton35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/25.png"))); // NOI18N
        jButton35.setText("10");
        jButton35.setBorder(null);
        jButton35.setBorderPainted(false);
        jButton35.setContentAreaFilled(false);
        jButton35.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton35.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton35.setVerifyInputWhenFocusTarget(false);
        jButton35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton35ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton35);
        jButton35.setBounds(570, 90, 40, 40);

        jButton36.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jButton36.setForeground(new java.awt.Color(240, 240, 240));
        jButton36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/25.png"))); // NOI18N
        jButton36.setText("17");
        jButton36.setBorder(null);
        jButton36.setBorderPainted(false);
        jButton36.setContentAreaFilled(false);
        jButton36.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton36.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton36.setVerifyInputWhenFocusTarget(false);
        jButton36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton36ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton36);
        jButton36.setBounds(830, 80, 40, 40);

        jButton37.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jButton37.setForeground(new java.awt.Color(240, 240, 240));
        jButton37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/25.png"))); // NOI18N
        jButton37.setText("3");
        jButton37.setBorder(null);
        jButton37.setBorderPainted(false);
        jButton37.setContentAreaFilled(false);
        jButton37.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton37.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton37.setVerifyInputWhenFocusTarget(false);
        jButton37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton37ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton37);
        jButton37.setBounds(130, 370, 40, 40);

        jButton38.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jButton38.setForeground(new java.awt.Color(240, 240, 240));
        jButton38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/25.png"))); // NOI18N
        jButton38.setText("8");
        jButton38.setBorder(null);
        jButton38.setBorderPainted(false);
        jButton38.setContentAreaFilled(false);
        jButton38.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton38.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton38.setVerifyInputWhenFocusTarget(false);
        jButton38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton38ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton38);
        jButton38.setBounds(480, 390, 40, 40);

        jButton39.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jButton39.setForeground(new java.awt.Color(240, 240, 240));
        jButton39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/25.png"))); // NOI18N
        jButton39.setText("22");
        jButton39.setBorder(null);
        jButton39.setBorderPainted(false);
        jButton39.setContentAreaFilled(false);
        jButton39.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton39.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton39.setVerifyInputWhenFocusTarget(false);
        jButton39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton39ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton39);
        jButton39.setBounds(840, 200, 40, 40);

        jButton40.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jButton40.setForeground(new java.awt.Color(240, 240, 240));
        jButton40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/25.png"))); // NOI18N
        jButton40.setText("11");
        jButton40.setBorder(null);
        jButton40.setBorderPainted(false);
        jButton40.setContentAreaFilled(false);
        jButton40.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton40.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton40.setVerifyInputWhenFocusTarget(false);
        jButton40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton40ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton40);
        jButton40.setBounds(580, 240, 40, 40);

        jButton41.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jButton41.setForeground(new java.awt.Color(240, 240, 240));
        jButton41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/25.png"))); // NOI18N
        jButton41.setText("7");
        jButton41.setBorder(null);
        jButton41.setBorderPainted(false);
        jButton41.setContentAreaFilled(false);
        jButton41.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton41.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton41.setVerifyInputWhenFocusTarget(false);
        jButton41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton41ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton41);
        jButton41.setBounds(480, 340, 40, 40);

        jButton42.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jButton42.setForeground(new java.awt.Color(240, 240, 240));
        jButton42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/25.png"))); // NOI18N
        jButton42.setText("13");
        jButton42.setBorder(null);
        jButton42.setBorderPainted(false);
        jButton42.setContentAreaFilled(false);
        jButton42.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton42.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton42.setVerifyInputWhenFocusTarget(false);
        jButton42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton42ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton42);
        jButton42.setBounds(620, 290, 40, 40);

        l1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        l1.setText("air conditioner");
        l1.setOpaque(true);
        getContentPane().add(l1);
        l1.setBounds(150, 10, 130, 22);

        l2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        l2.setText("skirt");
        l2.setOpaque(true);
        getContentPane().add(l2);
        l2.setBounds(110, 190, 70, 30);

        l3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        l3.setText("high heel shoes");
        l3.setOpaque(true);
        getContentPane().add(l3);
        l3.setBounds(100, 400, 140, 22);

        l4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        l4.setText(" bookcase");
        l4.setOpaque(true);
        getContentPane().add(l4);
        l4.setBounds(170, 370, 100, 22);

        l5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        l5.setText("books");
        l5.setOpaque(true);
        getContentPane().add(l5);
        l5.setBounds(270, 350, 70, 22);

        l6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        l6.setText("backpack");
        l6.setOpaque(true);
        getContentPane().add(l6);
        l6.setBounds(350, 310, 100, 22);

        l7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        l7.setText("short");
        l7.setOpaque(true);
        getContentPane().add(l7);
        l7.setBounds(520, 350, 80, 22);

        l8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        l8.setText("treasures");
        l8.setOpaque(true);
        getContentPane().add(l8);
        l8.setBounds(520, 400, 110, 22);

        l9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        l9.setText("offer");
        l9.setOpaque(true);
        getContentPane().add(l9);
        l9.setBounds(620, 40, 60, 22);

        l16.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        l16.setText("picture");
        l16.setOpaque(true);
        getContentPane().add(l16);
        l16.setBounds(820, 0, 80, 22);

        l15.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        l15.setText("shelf");
        l15.setOpaque(true);
        getContentPane().add(l15);
        l15.setBounds(790, 70, 70, 22);

        l11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        l11.setText("dress");
        l11.setOpaque(true);
        getContentPane().add(l11);
        l11.setBounds(620, 250, 80, 22);

        l17.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        l17.setText("cap");
        l17.setOpaque(true);
        getContentPane().add(l17);
        l17.setBounds(870, 90, 70, 22);

        l18.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        l18.setText("Code bar reader");
        l18.setOpaque(true);
        getContentPane().add(l18);
        l18.setBounds(650, 130, 140, 28);

        l22.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        l22.setText(" apron");
        l22.setOpaque(true);
        getContentPane().add(l22);
        l22.setBounds(870, 210, 90, 22);

        l23.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        l23.setText("monitor");
        l23.setOpaque(true);
        getContentPane().add(l23);
        l23.setBounds(930, 220, 90, 22);

        l24.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        l24.setText("keyboard");
        l24.setOpaque(true);
        getContentPane().add(l24);
        l24.setBounds(880, 270, 100, 22);

        l25.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        l25.setText(" counter");
        l25.setOpaque(true);
        getContentPane().add(l25);
        l25.setBounds(850, 370, 90, 22);

        l21.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        l21.setText("certification");
        l21.setOpaque(true);
        getContentPane().add(l21);
        l21.setBounds(700, 330, 110, 22);

        l13.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        l13.setText("plant");
        l13.setOpaque(true);
        getContentPane().add(l13);
        l13.setBounds(630, 280, 80, 22);

        l14.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        l14.setText("flower pot ");
        l14.setOpaque(true);
        getContentPane().add(l14);
        l14.setBounds(620, 370, 120, 22);

        l12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        l12.setText("credit card");
        l12.setOpaque(true);
        getContentPane().add(l12);
        l12.setBounds(590, 220, 110, 22);

        l19.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        l19.setText(" cash register");
        l19.setOpaque(true);
        getContentPane().add(l19);
        l19.setBounds(670, 210, 120, 22);

        l20.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        l20.setText("ticket printer ");
        l20.setOpaque(true);
        getContentPane().add(l20);
        l20.setBounds(710, 250, 120, 22);

        l10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        l10.setText("hat");
        l10.setOpaque(true);
        getContentPane().add(l10);
        l10.setBounds(620, 100, 70, 22);

        jSalir.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jSalir.setForeground(new java.awt.Color(240, 240, 240));
        jSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/45.png"))); // NOI18N
        jSalir.setText("<");
        jSalir.setBorder(null);
        jSalir.setBorderPainted(false);
        jSalir.setContentAreaFilled(false);
        jSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jSalir.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/35.png"))); // NOI18N
        jSalir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/40.png"))); // NOI18N
        jSalir.setVerifyInputWhenFocusTarget(false);
        jSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jSalir);
        jSalir.setBounds(10, 10, 31, 31);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondos/flibreria.jpg"))); // NOI18N
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1020, 470);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
 AudioClip sonido;
        sonido= java.applet.Applet.newAudioClip(getClass().getResource("/audio/cash register.wav"));
        sonido.play();        // TODO add your handling code here:
        l1.setVisible(false);
        l2.setVisible(false);
        l3.setVisible(false);
        l4.setVisible(false);
        l5.setVisible(false);
        l6.setVisible(false);
        l7.setVisible(false);
        l8.setVisible(false);
        l9.setVisible(false);
        l10.setVisible(false);
        l11.setVisible(false);
        l12.setVisible(false);
        l13.setVisible(false);
        l14.setVisible(false);
        l15.setVisible(false);
        l16.setVisible(false);
        l17.setVisible(false);
        l18.setVisible(false);
        l19.setVisible(true);
        l20.setVisible(false);
        l21.setVisible(false);
        l22.setVisible(false);
        l23.setVisible(false);
        l24.setVisible(false);
        l25.setVisible(false);
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
 AudioClip sonido;
        sonido= java.applet.Applet.newAudioClip(getClass().getResource("/audio/keyboard.wav"));
        sonido.play();        // TODO add your handling code here:
        l1.setVisible(false);
        l2.setVisible(false);
        l3.setVisible(false);
        l4.setVisible(false);
        l5.setVisible(false);
        l6.setVisible(false);
        l7.setVisible(false);
        l8.setVisible(false);
        l9.setVisible(false);
        l10.setVisible(false);
        l11.setVisible(false);
        l12.setVisible(false);
        l13.setVisible(false);
        l14.setVisible(false);
        l15.setVisible(false);
        l16.setVisible(false);
        l17.setVisible(false);
        l18.setVisible(false);
        l19.setVisible(false);
        l20.setVisible(false);
        l21.setVisible(false);
        l22.setVisible(false);
        l23.setVisible(false);
        l24.setVisible(true);
        l25.setVisible(false);
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
 AudioClip sonido;
        sonido= java.applet.Applet.newAudioClip(getClass().getResource("/audio/certification.wav"));
        sonido.play();        // TODO add your handling code here:
        l1.setVisible(false);
        l2.setVisible(false);
        l3.setVisible(false);
        l4.setVisible(false);
        l5.setVisible(false);
        l6.setVisible(false);
        l7.setVisible(false);
        l8.setVisible(false);
        l9.setVisible(false);
        l10.setVisible(false);
        l11.setVisible(false);
        l12.setVisible(false);
        l13.setVisible(false);
        l14.setVisible(false);
        l15.setVisible(false);
        l16.setVisible(false);
        l17.setVisible(false);
        l18.setVisible(false);
        l19.setVisible(false);
        l20.setVisible(false);
        l21.setVisible(true);
        l22.setVisible(false);
        l23.setVisible(false);
        l24.setVisible(false);
        l25.setVisible(false);
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
 AudioClip sonido;
        sonido= java.applet.Applet.newAudioClip(getClass().getResource("/audio/shelf.wav"));
        sonido.play();        // TODO add your handling code here:
        l1.setVisible(false);
        l2.setVisible(false);
        l3.setVisible(false);
        l4.setVisible(false);
        l5.setVisible(false);
        l6.setVisible(false);
        l7.setVisible(false);
        l8.setVisible(false);
        l9.setVisible(false);
        l10.setVisible(false);
        l11.setVisible(false);
        l12.setVisible(false);
        l13.setVisible(false);
        l14.setVisible(false);
        l15.setVisible(true);
        l16.setVisible(false);
        l17.setVisible(false);
        l18.setVisible(false);
        l19.setVisible(false);
        l20.setVisible(false);
        l21.setVisible(false);
        l22.setVisible(false);
        l23.setVisible(false);
        l24.setVisible(false);
        l25.setVisible(false);
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
         AudioClip sonido;
        sonido= java.applet.Applet.newAudioClip(getClass().getResource("/audio/offer.wav"));
        sonido.play(); // TODO add your handling code here:
        l1.setVisible(false);
        l2.setVisible(false);
        l3.setVisible(false);
        l4.setVisible(false);
        l5.setVisible(false);
        l6.setVisible(false);
        l7.setVisible(false);
        l8.setVisible(false);
        l9.setVisible(true);
        l10.setVisible(false);
        l11.setVisible(false);
        l12.setVisible(false);
        l13.setVisible(false);
        l14.setVisible(false);
        l15.setVisible(false);
        l16.setVisible(false);
        l17.setVisible(false);
        l18.setVisible(false);
        l19.setVisible(false);
        l20.setVisible(false);
        l21.setVisible(false);
        l22.setVisible(false);
        l23.setVisible(false);
        l24.setVisible(false);
        l25.setVisible(false);
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
 AudioClip sonido;
        sonido= java.applet.Applet.newAudioClip(getClass().getResource("/audio/flower pot.wav"));
        sonido.play();        // TODO add your handling code here:
        l1.setVisible(false);
        l2.setVisible(false);
        l3.setVisible(false);
        l4.setVisible(false);
        l5.setVisible(false);
        l6.setVisible(false);
        l7.setVisible(false);
        l8.setVisible(false);
        l9.setVisible(false);
        l10.setVisible(false);
        l11.setVisible(false);
        l12.setVisible(false);
        l13.setVisible(false);
        l14.setVisible(true);
        l15.setVisible(false);
        l16.setVisible(false);
        l17.setVisible(false);
        l18.setVisible(false);
        l19.setVisible(false);
        l20.setVisible(false);
        l21.setVisible(false);
        l22.setVisible(false);
        l23.setVisible(false);
        l24.setVisible(false);
        l25.setVisible(false);
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
 AudioClip sonido;
        sonido= java.applet.Applet.newAudioClip(getClass().getResource("/audio/counter.wav"));
        sonido.play();        // TODO add your handling code here:
        l1.setVisible(false);
        l2.setVisible(false);
        l3.setVisible(false);
        l4.setVisible(false);
        l5.setVisible(false);
        l6.setVisible(false);
        l7.setVisible(false);
        l8.setVisible(false);
        l9.setVisible(false);
        l10.setVisible(false);
        l11.setVisible(false);
        l12.setVisible(false);
        l13.setVisible(false);
        l14.setVisible(false);
        l15.setVisible(false);
        l16.setVisible(false);
        l17.setVisible(false);
        l18.setVisible(false);
        l19.setVisible(false);
        l20.setVisible(false);
        l21.setVisible(false);
        l22.setVisible(false);
        l23.setVisible(false);
        l24.setVisible(false);
        l25.setVisible(true);
    }//GEN-LAST:event_jButton24ActionPerformed

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
 AudioClip sonido;
        sonido= java.applet.Applet.newAudioClip(getClass().getResource("/audio/monitor.wav"));
        sonido.play();        // TODO add your handling code here:
        l1.setVisible(false);
        l2.setVisible(false);
        l3.setVisible(false);
        l4.setVisible(false);
        l5.setVisible(false);
        l6.setVisible(false);
        l7.setVisible(false);
        l8.setVisible(false);
        l9.setVisible(false);
        l10.setVisible(false);
        l11.setVisible(false);
        l12.setVisible(false);
        l13.setVisible(false);
        l14.setVisible(false);
        l15.setVisible(false);
        l16.setVisible(false);
        l17.setVisible(false);
        l18.setVisible(false);
        l19.setVisible(false);
        l20.setVisible(false);
        l21.setVisible(false);
        l22.setVisible(false);
        l23.setVisible(true);
        l24.setVisible(false);
        l25.setVisible(false);
    }//GEN-LAST:event_jButton25ActionPerformed

    private void q16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q16ActionPerformed
 AudioClip sonido;
        sonido= java.applet.Applet.newAudioClip(getClass().getResource("/audio/picture.wav"));
        sonido.play();        // TODO add your handling code here:
        l1.setVisible(false);
        l2.setVisible(false);
        l3.setVisible(false);
        l4.setVisible(false);
        l5.setVisible(false);
        l6.setVisible(false);
        l7.setVisible(false);
        l8.setVisible(false);
        l9.setVisible(false);
        l10.setVisible(false);
        l11.setVisible(false);
        l12.setVisible(false);
        l13.setVisible(false);
        l14.setVisible(false);
        l15.setVisible(false);
        l16.setVisible(true);
        l17.setVisible(false);
        l18.setVisible(false);
        l19.setVisible(false);
        l20.setVisible(false);
        l21.setVisible(false);
        l22.setVisible(false);
        l23.setVisible(false);
        l24.setVisible(false);
        l25.setVisible(false);
    }//GEN-LAST:event_q16ActionPerformed

    private void jButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton27ActionPerformed
 AudioClip sonido;
        sonido= java.applet.Applet.newAudioClip(getClass().getResource("/audio/skirt.wav"));
        sonido.play();        // TODO add your handling code here:
        l1.setVisible(false);
        l2.setVisible(true);
        l3.setVisible(false);
        l4.setVisible(false);
        l5.setVisible(false);
        l6.setVisible(false);
        l7.setVisible(false);
        l8.setVisible(false);
        l9.setVisible(false);
        l10.setVisible(false);
        l11.setVisible(false);
        l12.setVisible(false);
        l13.setVisible(false);
        l14.setVisible(false);
        l15.setVisible(false);
        l16.setVisible(false);
        l17.setVisible(false);
        l18.setVisible(false);
        l19.setVisible(false);
        l20.setVisible(false);
        l21.setVisible(false);
        l22.setVisible(false);
        l23.setVisible(false);
        l24.setVisible(false);
        l25.setVisible(false);
    }//GEN-LAST:event_jButton27ActionPerformed

    private void jButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton28ActionPerformed
 AudioClip sonido;
        sonido= java.applet.Applet.newAudioClip(getClass().getResource("/audio/code bar reader.wav"));
        sonido.play();        // TODO add your handling code here:
        l1.setVisible(false);
        l2.setVisible(false);
        l3.setVisible(false);
        l4.setVisible(false);
        l5.setVisible(false);
        l6.setVisible(false);
        l7.setVisible(false);
        l8.setVisible(false);
        l9.setVisible(false);
        l10.setVisible(false);
        l11.setVisible(false);
        l12.setVisible(false);
        l13.setVisible(false);
        l14.setVisible(false);
        l15.setVisible(false);
       l16.setVisible(false);
        l17.setVisible(false);
        l18.setVisible(true);
        l19.setVisible(false);
        l20.setVisible(false);
        l21.setVisible(false);
        l22.setVisible(false);
        l23.setVisible(false);
        l24.setVisible(false);
        l25.setVisible(false);
    }//GEN-LAST:event_jButton28ActionPerformed

    private void jButton29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton29ActionPerformed
 AudioClip sonido;
        sonido= java.applet.Applet.newAudioClip(getClass().getResource("/audio/books.wav"));
        sonido.play();        // TODO add your handling code here:
        l1.setVisible(false);
        l2.setVisible(false);
        l3.setVisible(false);
        l4.setVisible(false);
        l5.setVisible(true);
        l6.setVisible(false);
        l7.setVisible(false);
        l8.setVisible(false);
        l9.setVisible(false);
        l10.setVisible(false);
        l11.setVisible(false);
        l12.setVisible(false);
        l13.setVisible(false);
        l14.setVisible(false);
        l15.setVisible(false);
        l16.setVisible(false);
        l17.setVisible(false);
        l18.setVisible(false);
        l19.setVisible(false);
        l20.setVisible(false);
        l21.setVisible(false);
        l22.setVisible(false);
        l23.setVisible(false);
        l24.setVisible(false);
        l25.setVisible(false);
    }//GEN-LAST:event_jButton29ActionPerformed

    private void jButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton30ActionPerformed
 AudioClip sonido;
        sonido= java.applet.Applet.newAudioClip(getClass().getResource("/audio/ticket printer.wav"));
        sonido.play();        // TODO add your handling code here:
        l1.setVisible(false);
        l2.setVisible(false);
        l3.setVisible(false);
        l4.setVisible(false);
        l5.setVisible(false);
        l6.setVisible(false);
        l7.setVisible(false);
        l8.setVisible(false);
        l9.setVisible(false);
        l10.setVisible(false);
        l11.setVisible(false);
        l12.setVisible(false);
        l13.setVisible(false);
        l14.setVisible(false);
        l15.setVisible(false);
        l16.setVisible(false);
        l17.setVisible(false);
        l18.setVisible(false);
        l19.setVisible(false);
        l20.setVisible(true);
        l21.setVisible(false);
        l22.setVisible(false);
        l23.setVisible(false);
        l24.setVisible(false);
        l25.setVisible(false);
    }//GEN-LAST:event_jButton30ActionPerformed

    private void jButton31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton31ActionPerformed
 AudioClip sonido;
        sonido= java.applet.Applet.newAudioClip(getClass().getResource("/audio/air conditioner.wav"));
        sonido.play();        // TODO add your handling code here:
        l1.setVisible(true);
        l2.setVisible(false);
        l3.setVisible(false);
        l4.setVisible(false);
        l5.setVisible(false);
        l6.setVisible(false);
        l7.setVisible(false);
        l8.setVisible(false);
        l9.setVisible(false);
        l10.setVisible(false);
        l11.setVisible(false);
        l12.setVisible(false);
        l13.setVisible(false);
        l14.setVisible(false);
        l15.setVisible(false);
        l16.setVisible(false);
        l17.setVisible(false);
        l18.setVisible(false);
        l19.setVisible(false);
        l20.setVisible(false);
        l21.setVisible(false);
        l22.setVisible(false);
        l23.setVisible(false);
        l24.setVisible(false);
        l25.setVisible(false);
    }//GEN-LAST:event_jButton31ActionPerformed

    private void jButton32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton32ActionPerformed
 AudioClip sonido;
        sonido= java.applet.Applet.newAudioClip(getClass().getResource("/audio/book case.wav"));
        sonido.play();        // TODO add your handling code here:
        l1.setVisible(false);
        l2.setVisible(false);
        l3.setVisible(false);
        l4.setVisible(true);
        l5.setVisible(false);
        l6.setVisible(false);
        l7.setVisible(false);
        l8.setVisible(false);
        l9.setVisible(false);
        l10.setVisible(false);
        l11.setVisible(false);
        l12.setVisible(false);
        l13.setVisible(false);
        l14.setVisible(false);
        l15.setVisible(false);
        l16.setVisible(false);
        l17.setVisible(false);
        l18.setVisible(false);
        l19.setVisible(false);
        l20.setVisible(false);
        l21.setVisible(false);
        l22.setVisible(false);
        l23.setVisible(false);
        l24.setVisible(false);
        l25.setVisible(false);
    }//GEN-LAST:event_jButton32ActionPerformed

    private void jButton33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton33ActionPerformed
 AudioClip sonido;
        sonido= java.applet.Applet.newAudioClip(getClass().getResource("/audio/credit card.wav"));
        sonido.play();        // TODO add your handling code here:
        l1.setVisible(false);
        l2.setVisible(false);
        l3.setVisible(false);
        l4.setVisible(false);
        l5.setVisible(false);
        l6.setVisible(false);
        l7.setVisible(false);
        l8.setVisible(false);
        l9.setVisible(false);
        l10.setVisible(false);
        l11.setVisible(false);
        l12.setVisible(true);
        l13.setVisible(false);
        l14.setVisible(false);
        l15.setVisible(false);
        l16.setVisible(false);
        l17.setVisible(false);
        l18.setVisible(false);
        l19.setVisible(false);
        l20.setVisible(false);
        l21.setVisible(false);
        l22.setVisible(false);
        l23.setVisible(false);
        l24.setVisible(false);
        l25.setVisible(false);
    }//GEN-LAST:event_jButton33ActionPerformed

    private void jButton34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton34ActionPerformed
 AudioClip sonido;
        sonido= java.applet.Applet.newAudioClip(getClass().getResource("/audio/backpack.wav"));
        sonido.play();        // TODO add your handling code here:
        l1.setVisible(false);
        l2.setVisible(false);
        l3.setVisible(false);
        l4.setVisible(false);
        l5.setVisible(false);
        l6.setVisible(true);
        l7.setVisible(false);
        l8.setVisible(false);
        l9.setVisible(false);
        l10.setVisible(false);
        l11.setVisible(false);
        l12.setVisible(false);
        l13.setVisible(false);
        l14.setVisible(false);
        l15.setVisible(false);
        l16.setVisible(false);
        l17.setVisible(false);
        l18.setVisible(false);
        l19.setVisible(false);
        l20.setVisible(false);
        l21.setVisible(false);
        l22.setVisible(false);
        l23.setVisible(false);
        l24.setVisible(false);
        l25.setVisible(false);
    }//GEN-LAST:event_jButton34ActionPerformed

    private void jButton35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton35ActionPerformed
 AudioClip sonido;
        sonido= java.applet.Applet.newAudioClip(getClass().getResource("/audio/hat.wav"));
        sonido.play();        // TODO add your handling code here:
        l1.setVisible(false);
        l2.setVisible(false);
        l3.setVisible(false);
        l4.setVisible(false);
        l5.setVisible(false);
        l6.setVisible(false);
        l7.setVisible(false);
        l8.setVisible(false);
        l9.setVisible(false);
        l10.setVisible(true);
        l11.setVisible(false);
        l12.setVisible(false);
        l13.setVisible(false);
        l14.setVisible(false);
        l15.setVisible(false);
        l16.setVisible(false);
        l17.setVisible(false);
        l18.setVisible(false);
        l19.setVisible(false);
        l20.setVisible(false);
        l21.setVisible(false);
        l22.setVisible(false);
        l23.setVisible(false);
        l24.setVisible(false);
        l25.setVisible(false);
    }//GEN-LAST:event_jButton35ActionPerformed

    private void jButton36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton36ActionPerformed
 AudioClip sonido;
        sonido= java.applet.Applet.newAudioClip(getClass().getResource("/audio/cap.wav"));
        sonido.play();        // TODO add your handling code here:
        l1.setVisible(false);
        l2.setVisible(false);
        l3.setVisible(false);
        l4.setVisible(false);
        l5.setVisible(false);
        l6.setVisible(false);
        l7.setVisible(false);
        l8.setVisible(false);
        l9.setVisible(false);
        l10.setVisible(false);
        l11.setVisible(false);
        l12.setVisible(false);
        l13.setVisible(false);
        l14.setVisible(false);
        l15.setVisible(false);
        l16.setVisible(false);
        l17.setVisible(true);
        l18.setVisible(false);
        l19.setVisible(false);
        l20.setVisible(false);
        l21.setVisible(false);
        l22.setVisible(false);
        l23.setVisible(false);
        l24.setVisible(false);
        l25.setVisible(false);
    }//GEN-LAST:event_jButton36ActionPerformed

    private void jButton37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton37ActionPerformed
 AudioClip sonido;
        sonido= java.applet.Applet.newAudioClip(getClass().getResource("/audio/high heel shoes.wav"));
        sonido.play();        // TODO add your handling code here:
        l1.setVisible(false);
        l2.setVisible(false);
        l3.setVisible(true);
        l4.setVisible(false);
        l5.setVisible(false);
        l6.setVisible(false);
        l7.setVisible(false);
        l8.setVisible(false);
        l9.setVisible(false);
        l10.setVisible(false);
        l11.setVisible(false);
        l12.setVisible(false);
        l13.setVisible(false);
        l14.setVisible(false);
        l15.setVisible(false);
        l16.setVisible(false);
        l17.setVisible(false);
        l18.setVisible(false);
        l19.setVisible(false);
        l20.setVisible(false);
        l21.setVisible(false);
        l22.setVisible(false);
        l23.setVisible(false);
        l24.setVisible(false);
        l25.setVisible(false);
    }//GEN-LAST:event_jButton37ActionPerformed

    private void jButton38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton38ActionPerformed
 AudioClip sonido;
        sonido= java.applet.Applet.newAudioClip(getClass().getResource("/audio/treasures.wav"));
        sonido.play();        // TODO add your handling code here:
        l1.setVisible(false);
        l2.setVisible(false);
        l3.setVisible(false);
        l4.setVisible(false);
        l5.setVisible(false);
        l6.setVisible(false);
        l7.setVisible(false);
        l8.setVisible(true);
        l9.setVisible(false);
        l10.setVisible(false);
        l11.setVisible(false);
        l12.setVisible(false);
        l13.setVisible(false);
        l14.setVisible(false);
        l15.setVisible(false);
        l16.setVisible(false);
        l17.setVisible(false);
        l18.setVisible(false);
        l19.setVisible(false);
        l20.setVisible(false);
        l21.setVisible(false);
        l22.setVisible(false);
        l23.setVisible(false);
        l24.setVisible(false);
        l25.setVisible(false);
    }//GEN-LAST:event_jButton38ActionPerformed

    private void jButton39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton39ActionPerformed
 AudioClip sonido;
        sonido= java.applet.Applet.newAudioClip(getClass().getResource("/audio/apron.wav"));
        sonido.play();        // TODO add your handling code here:
        l1.setVisible(false);
        l2.setVisible(false);
        l3.setVisible(false);
        l4.setVisible(false);
        l5.setVisible(false);
        l6.setVisible(false);
        l7.setVisible(false);
        l8.setVisible(false);
        l9.setVisible(false);
        l10.setVisible(false);
        l11.setVisible(false);
        l12.setVisible(false);
        l13.setVisible(false);
        l14.setVisible(false);
        l15.setVisible(false);
        l16.setVisible(false);
        l17.setVisible(false);
        l18.setVisible(false);
        l19.setVisible(false);
        l20.setVisible(false);
        l21.setVisible(false);
        l22.setVisible(true);
        l23.setVisible(false);
        l24.setVisible(false);
        l25.setVisible(false);
    }//GEN-LAST:event_jButton39ActionPerformed

    private void jButton40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton40ActionPerformed
 AudioClip sonido;
        sonido= java.applet.Applet.newAudioClip(getClass().getResource("/audio/dress.wav"));
        sonido.play();        // TODO add your handling code here:
        l1.setVisible(false);
        l2.setVisible(false);
        l3.setVisible(false);
        l4.setVisible(false);
        l5.setVisible(false);
        l6.setVisible(false);
        l7.setVisible(false);
        l8.setVisible(false);
        l9.setVisible(false);
        l10.setVisible(false);
        l11.setVisible(true);
        l12.setVisible(false);
        l13.setVisible(false);
        l14.setVisible(false);
        l15.setVisible(false);
        l16.setVisible(false);
        l17.setVisible(false);
        l18.setVisible(false);
        l19.setVisible(false);
        l20.setVisible(false);
        l21.setVisible(false);
        l22.setVisible(false);
        l23.setVisible(false);
        l24.setVisible(false);
        l25.setVisible(false);
    }//GEN-LAST:event_jButton40ActionPerformed

    private void jButton41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton41ActionPerformed
 AudioClip sonido;
        sonido= java.applet.Applet.newAudioClip(getClass().getResource("/audio/short.wav"));
        sonido.play();        // TODO add your handling code here:
        l1.setVisible(false);
        l2.setVisible(false);
        l3.setVisible(false);
        l4.setVisible(false);
        l5.setVisible(false);
        l6.setVisible(false);
        l7.setVisible(true);
        l8.setVisible(false);
        l9.setVisible(false);
        l10.setVisible(false);
        l11.setVisible(false);
        l12.setVisible(false);
        l13.setVisible(false);
        l14.setVisible(false);
        l15.setVisible(false);
        l16.setVisible(false);
        l17.setVisible(false);
        l18.setVisible(false);
        l19.setVisible(false);
        l20.setVisible(false);
        l21.setVisible(false);
        l22.setVisible(false);
        l23.setVisible(false);
        l24.setVisible(false);
        l25.setVisible(false);
    }//GEN-LAST:event_jButton41ActionPerformed

    private void jButton42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton42ActionPerformed
 AudioClip sonido;
        sonido= java.applet.Applet.newAudioClip(getClass().getResource("/audio/plant.wav"));
        sonido.play();        // TODO add your handling code here:
        l1.setVisible(false);
        l2.setVisible(false);
        l3.setVisible(false);
        l4.setVisible(false);
        l5.setVisible(false);
        l6.setVisible(false);
        l7.setVisible(false);
        l8.setVisible(false);
        l9.setVisible(false);
        l10.setVisible(false);
        l11.setVisible(false);
        l12.setVisible(false);
        l13.setVisible(true);
        l14.setVisible(false);
        l15.setVisible(false);
        l16.setVisible(false);
        l17.setVisible(false);
        l18.setVisible(false);
        l19.setVisible(false);
        l20.setVisible(false);
        l21.setVisible(false);
        l22.setVisible(false);
        l23.setVisible(false);
        l24.setVisible(false);
        l25.setVisible(false);
    }//GEN-LAST:event_jButton42ActionPerformed

    private void jSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSalirActionPerformed
        new Menu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Libreria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Libreria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Libreria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Libreria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Libreria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton42;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jSalir;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l10;
    private javax.swing.JLabel l11;
    private javax.swing.JLabel l12;
    private javax.swing.JLabel l13;
    private javax.swing.JLabel l14;
    private javax.swing.JLabel l15;
    private javax.swing.JLabel l16;
    private javax.swing.JLabel l17;
    private javax.swing.JLabel l18;
    private javax.swing.JLabel l19;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l20;
    private javax.swing.JLabel l21;
    private javax.swing.JLabel l22;
    private javax.swing.JLabel l23;
    private javax.swing.JLabel l24;
    private javax.swing.JLabel l25;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel l5;
    private javax.swing.JLabel l6;
    private javax.swing.JLabel l7;
    private javax.swing.JLabel l8;
    private javax.swing.JLabel l9;
    private javax.swing.JButton q16;
    // End of variables declaration//GEN-END:variables
}
