package Modulos;

import java.applet.AudioClip;

public class Optica extends javax.swing.JFrame {

    /**
     * Creates new form Optica
     */
    public Optica() {
        initComponents();
        this.setSize(955,490);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        a1.setVisible(false);
        a2.setVisible(false);
        a3.setVisible(false);
        a4.setVisible(false);
        a5.setVisible(false);
        a6.setVisible(false);
        a7.setVisible(false);
        a8.setVisible(false);
        a9.setVisible(false);
        a10.setVisible(false);
        a11.setVisible(false);
        a111.setVisible(false);
        a12.setVisible(false);
        a13.setVisible(false);
        a14.setVisible(false);
        a15.setVisible(false);
        a16.setVisible(false);
        a17.setVisible(false);
        a18.setVisible(false);
        a19.setVisible(false);
        a20.setVisible(false);
        a21.setVisible(false);
        a22.setVisible(false);
        a23.setVisible(false);
        a24.setVisible(false);
        a25.setVisible(false);
        
        
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton18 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        a25 = new javax.swing.JLabel();
        a1 = new javax.swing.JLabel();
        a2 = new javax.swing.JLabel();
        a3 = new javax.swing.JLabel();
        a4 = new javax.swing.JLabel();
        a5 = new javax.swing.JLabel();
        a10 = new javax.swing.JLabel();
        a9 = new javax.swing.JLabel();
        a8 = new javax.swing.JLabel();
        a7 = new javax.swing.JLabel();
        a13 = new javax.swing.JLabel();
        a12 = new javax.swing.JLabel();
        a22 = new javax.swing.JLabel();
        a17 = new javax.swing.JLabel();
        a15 = new javax.swing.JLabel();
        a111 = new javax.swing.JLabel();
        a16 = new javax.swing.JLabel();
        a18 = new javax.swing.JLabel();
        a24 = new javax.swing.JLabel();
        a21 = new javax.swing.JLabel();
        a14 = new javax.swing.JLabel();
        a20 = new javax.swing.JLabel();
        a19 = new javax.swing.JLabel();
        a6 = new javax.swing.JLabel();
        a11 = new javax.swing.JLabel();
        a23 = new javax.swing.JLabel();
        jSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jButton18.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton18.setForeground(new java.awt.Color(255, 255, 255));
        jButton18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/45.png"))); // NOI18N
        jButton18.setText("1");
        jButton18.setToolTipText("");
        jButton18.setBorder(null);
        jButton18.setBorderPainted(false);
        jButton18.setContentAreaFilled(false);
        jButton18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton18.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton18.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/35.png"))); // NOI18N
        jButton18.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/40.png"))); // NOI18N
        jButton18.setVerifyInputWhenFocusTarget(false);
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton18);
        jButton18.setBounds(20, 330, 40, 30);

        jButton6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/45.png"))); // NOI18N
        jButton6.setText("2");
        jButton6.setBorder(null);
        jButton6.setBorderPainted(false);
        jButton6.setContentAreaFilled(false);
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/35.png"))); // NOI18N
        jButton6.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/40.png"))); // NOI18N
        jButton6.setVerifyInputWhenFocusTarget(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(360, 20, 40, 30);

        jButton5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/45.png"))); // NOI18N
        jButton5.setText("3");
        jButton5.setBorder(null);
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/35.png"))); // NOI18N
        jButton5.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/40.png"))); // NOI18N
        jButton5.setVerifyInputWhenFocusTarget(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(30, 210, 40, 30);

        jButton7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/45.png"))); // NOI18N
        jButton7.setText("4");
        jButton7.setBorder(null);
        jButton7.setBorderPainted(false);
        jButton7.setContentAreaFilled(false);
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton7.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/35.png"))); // NOI18N
        jButton7.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/40.png"))); // NOI18N
        jButton7.setVerifyInputWhenFocusTarget(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(180, 370, 40, 30);

        jButton8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/45.png"))); // NOI18N
        jButton8.setText("5");
        jButton8.setBorder(null);
        jButton8.setBorderPainted(false);
        jButton8.setContentAreaFilled(false);
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton8.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/35.png"))); // NOI18N
        jButton8.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/40.png"))); // NOI18N
        jButton8.setVerifyInputWhenFocusTarget(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8);
        jButton8.setBounds(290, 140, 40, 30);

        jButton9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/45.png"))); // NOI18N
        jButton9.setText("6");
        jButton9.setBorder(null);
        jButton9.setBorderPainted(false);
        jButton9.setContentAreaFilled(false);
        jButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton9.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/35.png"))); // NOI18N
        jButton9.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/40.png"))); // NOI18N
        jButton9.setVerifyInputWhenFocusTarget(false);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9);
        jButton9.setBounds(470, 170, 40, 30);

        jButton10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/45.png"))); // NOI18N
        jButton10.setText("25");
        jButton10.setBorder(null);
        jButton10.setBorderPainted(false);
        jButton10.setContentAreaFilled(false);
        jButton10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton10.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/35.png"))); // NOI18N
        jButton10.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/40.png"))); // NOI18N
        jButton10.setVerifyInputWhenFocusTarget(false);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton10);
        jButton10.setBounds(470, 280, 40, 30);

        jButton11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton11.setForeground(new java.awt.Color(255, 255, 255));
        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/45.png"))); // NOI18N
        jButton11.setText("7");
        jButton11.setBorder(null);
        jButton11.setBorderPainted(false);
        jButton11.setContentAreaFilled(false);
        jButton11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton11.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/35.png"))); // NOI18N
        jButton11.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/40.png"))); // NOI18N
        jButton11.setVerifyInputWhenFocusTarget(false);
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton11);
        jButton11.setBounds(410, 340, 40, 30);

        jButton12.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton12.setForeground(new java.awt.Color(255, 255, 255));
        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/45.png"))); // NOI18N
        jButton12.setText("8");
        jButton12.setBorder(null);
        jButton12.setBorderPainted(false);
        jButton12.setContentAreaFilled(false);
        jButton12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton12.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/35.png"))); // NOI18N
        jButton12.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/40.png"))); // NOI18N
        jButton12.setVerifyInputWhenFocusTarget(false);
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton12);
        jButton12.setBounds(730, 270, 40, 30);

        jButton13.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton13.setForeground(new java.awt.Color(255, 255, 255));
        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/45.png"))); // NOI18N
        jButton13.setText("9");
        jButton13.setBorder(null);
        jButton13.setBorderPainted(false);
        jButton13.setContentAreaFilled(false);
        jButton13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton13.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/35.png"))); // NOI18N
        jButton13.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/40.png"))); // NOI18N
        jButton13.setVerifyInputWhenFocusTarget(false);
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton13);
        jButton13.setBounds(580, 360, 40, 30);

        jButton14.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton14.setForeground(new java.awt.Color(255, 255, 255));
        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/45.png"))); // NOI18N
        jButton14.setText("10");
        jButton14.setBorder(null);
        jButton14.setBorderPainted(false);
        jButton14.setContentAreaFilled(false);
        jButton14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton14.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/35.png"))); // NOI18N
        jButton14.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/40.png"))); // NOI18N
        jButton14.setVerifyInputWhenFocusTarget(false);
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton14);
        jButton14.setBounds(670, 150, 40, 30);

        jButton15.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton15.setForeground(new java.awt.Color(255, 255, 255));
        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/45.png"))); // NOI18N
        jButton15.setText("11");
        jButton15.setBorder(null);
        jButton15.setBorderPainted(false);
        jButton15.setContentAreaFilled(false);
        jButton15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton15.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/35.png"))); // NOI18N
        jButton15.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/40.png"))); // NOI18N
        jButton15.setVerifyInputWhenFocusTarget(false);
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton15);
        jButton15.setBounds(820, 70, 40, 30);

        jButton16.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton16.setForeground(new java.awt.Color(255, 255, 255));
        jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/45.png"))); // NOI18N
        jButton16.setText("12");
        jButton16.setBorder(null);
        jButton16.setBorderPainted(false);
        jButton16.setContentAreaFilled(false);
        jButton16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton16.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton16.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/35.png"))); // NOI18N
        jButton16.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/40.png"))); // NOI18N
        jButton16.setVerifyInputWhenFocusTarget(false);
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton16);
        jButton16.setBounds(810, 210, 40, 30);

        jButton17.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton17.setForeground(new java.awt.Color(255, 255, 255));
        jButton17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/45.png"))); // NOI18N
        jButton17.setText("13");
        jButton17.setBorder(null);
        jButton17.setBorderPainted(false);
        jButton17.setContentAreaFilled(false);
        jButton17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton17.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton17.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/35.png"))); // NOI18N
        jButton17.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/40.png"))); // NOI18N
        jButton17.setVerifyInputWhenFocusTarget(false);
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton17);
        jButton17.setBounds(880, 270, 40, 30);

        jButton19.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton19.setForeground(new java.awt.Color(255, 255, 255));
        jButton19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/45.png"))); // NOI18N
        jButton19.setText("14");
        jButton19.setBorder(null);
        jButton19.setBorderPainted(false);
        jButton19.setContentAreaFilled(false);
        jButton19.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton19.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton19.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/35.png"))); // NOI18N
        jButton19.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/40.png"))); // NOI18N
        jButton19.setVerifyInputWhenFocusTarget(false);
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton19);
        jButton19.setBounds(910, 420, 40, 30);

        jButton20.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton20.setForeground(new java.awt.Color(255, 255, 255));
        jButton20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/45.png"))); // NOI18N
        jButton20.setText("15");
        jButton20.setBorder(null);
        jButton20.setBorderPainted(false);
        jButton20.setContentAreaFilled(false);
        jButton20.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton20.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton20.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/35.png"))); // NOI18N
        jButton20.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/40.png"))); // NOI18N
        jButton20.setVerifyInputWhenFocusTarget(false);
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton20);
        jButton20.setBounds(410, 90, 40, 30);

        jButton21.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton21.setForeground(new java.awt.Color(255, 255, 255));
        jButton21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/45.png"))); // NOI18N
        jButton21.setText("16");
        jButton21.setBorder(null);
        jButton21.setBorderPainted(false);
        jButton21.setContentAreaFilled(false);
        jButton21.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton21.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton21.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/35.png"))); // NOI18N
        jButton21.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/40.png"))); // NOI18N
        jButton21.setVerifyInputWhenFocusTarget(false);
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton21);
        jButton21.setBounds(360, 420, 40, 30);

        jButton22.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton22.setForeground(new java.awt.Color(255, 255, 255));
        jButton22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/45.png"))); // NOI18N
        jButton22.setText("17");
        jButton22.setBorder(null);
        jButton22.setBorderPainted(false);
        jButton22.setContentAreaFilled(false);
        jButton22.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton22.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton22.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/35.png"))); // NOI18N
        jButton22.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/40.png"))); // NOI18N
        jButton22.setVerifyInputWhenFocusTarget(false);
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton22);
        jButton22.setBounds(910, 220, 40, 30);

        jButton23.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton23.setForeground(new java.awt.Color(255, 255, 255));
        jButton23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/45.png"))); // NOI18N
        jButton23.setText("18");
        jButton23.setBorder(null);
        jButton23.setBorderPainted(false);
        jButton23.setContentAreaFilled(false);
        jButton23.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton23.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton23.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/35.png"))); // NOI18N
        jButton23.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/40.png"))); // NOI18N
        jButton23.setVerifyInputWhenFocusTarget(false);
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton23);
        jButton23.setBounds(850, 150, 40, 30);

        jButton24.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton24.setForeground(new java.awt.Color(255, 255, 255));
        jButton24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/45.png"))); // NOI18N
        jButton24.setText("24");
        jButton24.setBorder(null);
        jButton24.setBorderPainted(false);
        jButton24.setContentAreaFilled(false);
        jButton24.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton24.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton24.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/35.png"))); // NOI18N
        jButton24.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/40.png"))); // NOI18N
        jButton24.setVerifyInputWhenFocusTarget(false);
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton24);
        jButton24.setBounds(900, 130, 40, 30);

        jButton25.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton25.setForeground(new java.awt.Color(255, 255, 255));
        jButton25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/45.png"))); // NOI18N
        jButton25.setText("19");
        jButton25.setBorder(null);
        jButton25.setBorderPainted(false);
        jButton25.setContentAreaFilled(false);
        jButton25.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton25.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton25.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/35.png"))); // NOI18N
        jButton25.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/40.png"))); // NOI18N
        jButton25.setVerifyInputWhenFocusTarget(false);
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton25);
        jButton25.setBounds(600, 80, 40, 30);

        jButton26.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton26.setForeground(new java.awt.Color(255, 255, 255));
        jButton26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/45.png"))); // NOI18N
        jButton26.setText("20");
        jButton26.setBorder(null);
        jButton26.setBorderPainted(false);
        jButton26.setContentAreaFilled(false);
        jButton26.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton26.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton26.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/35.png"))); // NOI18N
        jButton26.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/40.png"))); // NOI18N
        jButton26.setVerifyInputWhenFocusTarget(false);
        jButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton26ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton26);
        jButton26.setBounds(640, 280, 40, 30);

        jButton27.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton27.setForeground(new java.awt.Color(255, 255, 255));
        jButton27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/45.png"))); // NOI18N
        jButton27.setText("21");
        jButton27.setBorder(null);
        jButton27.setBorderPainted(false);
        jButton27.setContentAreaFilled(false);
        jButton27.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton27.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton27.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/35.png"))); // NOI18N
        jButton27.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/40.png"))); // NOI18N
        jButton27.setVerifyInputWhenFocusTarget(false);
        jButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton27ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton27);
        jButton27.setBounds(260, 230, 40, 30);

        jButton28.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton28.setForeground(new java.awt.Color(255, 255, 255));
        jButton28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/45.png"))); // NOI18N
        jButton28.setText("22");
        jButton28.setBorder(null);
        jButton28.setBorderPainted(false);
        jButton28.setContentAreaFilled(false);
        jButton28.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton28.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton28.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/35.png"))); // NOI18N
        jButton28.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/40.png"))); // NOI18N
        jButton28.setVerifyInputWhenFocusTarget(false);
        jButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton28ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton28);
        jButton28.setBounds(120, 50, 40, 30);

        jButton29.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton29.setForeground(new java.awt.Color(255, 255, 255));
        jButton29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/45.png"))); // NOI18N
        jButton29.setText("23");
        jButton29.setBorder(null);
        jButton29.setBorderPainted(false);
        jButton29.setContentAreaFilled(false);
        jButton29.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton29.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton29.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/35.png"))); // NOI18N
        jButton29.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/40.png"))); // NOI18N
        jButton29.setVerifyInputWhenFocusTarget(false);
        jButton29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton29ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton29);
        jButton29.setBounds(800, 350, 40, 30);

        a25.setBackground(new java.awt.Color(204, 204, 204));
        a25.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        a25.setText("EYE");
        a25.setOpaque(true);
        jPanel1.add(a25);
        a25.setBounds(260, 250, 70, 50);

        a1.setBackground(new java.awt.Color(204, 204, 204));
        a1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        a1.setText("MIRROR");
        a1.setOpaque(true);
        jPanel1.add(a1);
        a1.setBounds(80, 200, 110, 28);

        a2.setBackground(new java.awt.Color(204, 204, 204));
        a2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        a2.setText("GLASSES");
        a2.setOpaque(true);
        jPanel1.add(a2);
        a2.setBounds(70, 310, 120, 28);

        a3.setBackground(new java.awt.Color(204, 204, 204));
        a3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        a3.setText("SHELVES");
        a3.setOpaque(true);
        jPanel1.add(a3);
        a3.setBounds(230, 370, 130, 28);

        a4.setBackground(new java.awt.Color(204, 204, 204));
        a4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        a4.setText("ILUMINATION");
        a4.setOpaque(true);
        jPanel1.add(a4);
        a4.setBounds(410, 20, 190, 28);

        a5.setBackground(new java.awt.Color(204, 204, 204));
        a5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        a5.setText("PHOTO");
        a5.setOpaque(true);
        jPanel1.add(a5);
        a5.setBounds(200, 110, 100, 28);

        a10.setBackground(new java.awt.Color(204, 204, 204));
        a10.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        a10.setText("SEAT");
        a10.setOpaque(true);
        jPanel1.add(a10);
        a10.setBounds(410, 420, 70, 28);

        a9.setBackground(new java.awt.Color(204, 204, 204));
        a9.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        a9.setText("PATIENT");
        a9.setOpaque(true);
        jPanel1.add(a9);
        a9.setBounds(450, 330, 110, 28);

        a8.setBackground(new java.awt.Color(204, 204, 204));
        a8.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        a8.setText("OPHTHALMOLOGIST");
        a8.setOpaque(true);
        jPanel1.add(a8);
        a8.setBounds(390, 240, 270, 28);

        a7.setBackground(new java.awt.Color(204, 204, 204));
        a7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        a7.setText("ZOOM LENSES");
        a7.setOpaque(true);
        jPanel1.add(a7);
        a7.setBounds(410, 130, 190, 28);

        a13.setBackground(new java.awt.Color(204, 204, 204));
        a13.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        a13.setText("CLOCK");
        a13.setOpaque(true);
        jPanel1.add(a13);
        a13.setBounds(780, 30, 110, 28);

        a12.setBackground(new java.awt.Color(204, 204, 204));
        a12.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        a12.setText("OPTOMETRIC CHART");
        a12.setOpaque(true);
        jPanel1.add(a12);
        a12.setBounds(650, 120, 270, 28);

        a22.setBackground(new java.awt.Color(204, 204, 204));
        a22.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        a22.setText("BOX");
        a22.setOpaque(true);
        jPanel1.add(a22);
        a22.setBounds(800, 130, 90, 28);

        a17.setBackground(new java.awt.Color(204, 204, 204));
        a17.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        a17.setText("CHAIR");
        a17.setOpaque(true);
        jPanel1.add(a17);
        a17.setBounds(790, 390, 80, 28);

        a15.setBackground(new java.awt.Color(204, 204, 204));
        a15.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        a15.setText("NURSE");
        a15.setOpaque(true);
        jPanel1.add(a15);
        a15.setBounds(690, 300, 100, 28);

        a111.setBackground(new java.awt.Color(204, 204, 204));
        a111.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        a111.setText("FURNITURE");
        a111.setOpaque(true);
        jPanel1.add(a111);
        a111.setBounds(520, 420, 160, 30);

        a16.setBackground(new java.awt.Color(204, 204, 204));
        a16.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        a16.setText("COMPUTER");
        a16.setOpaque(true);
        jPanel1.add(a16);
        a16.setBounds(810, 300, 140, 28);

        a18.setBackground(new java.awt.Color(204, 204, 204));
        a18.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        a18.setText("AIR CONDITIONER");
        a18.setOpaque(true);
        jPanel1.add(a18);
        a18.setBounds(160, 60, 240, 50);

        a24.setBackground(new java.awt.Color(204, 204, 204));
        a24.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        a24.setText("DRAWER");
        a24.setOpaque(true);
        jPanel1.add(a24);
        a24.setBounds(590, 300, 120, 40);

        a21.setBackground(new java.awt.Color(204, 204, 204));
        a21.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        a21.setText("PENCILS");
        a21.setOpaque(true);
        jPanel1.add(a21);
        a21.setBounds(790, 110, 130, 28);

        a14.setBackground(new java.awt.Color(204, 204, 204));
        a14.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        a14.setText("NOTES");
        a14.setOpaque(true);
        jPanel1.add(a14);
        a14.setBounds(780, 240, 110, 28);

        a20.setBackground(new java.awt.Color(204, 204, 204));
        a20.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        a20.setText("MARKERS");
        a20.setOpaque(true);
        jPanel1.add(a20);
        a20.setBounds(820, 180, 190, 28);

        a19.setBackground(new java.awt.Color(204, 204, 204));
        a19.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        a19.setText("TABLE");
        a19.setOpaque(true);
        jPanel1.add(a19);
        a19.setBounds(830, 430, 190, 28);

        a6.setBackground(new java.awt.Color(204, 204, 204));
        a6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        a6.setText("LAMP");
        a6.setOpaque(true);
        jPanel1.add(a6);
        a6.setBounds(350, 70, 90, 28);

        a11.setBackground(new java.awt.Color(204, 204, 204));
        a11.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        a11.setText("OPHTHALMOLOGICAL");
        a11.setOpaque(true);
        jPanel1.add(a11);
        a11.setBounds(490, 390, 280, 30);

        a23.setBackground(new java.awt.Color(204, 204, 204));
        a23.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        a23.setText("SCREW");
        a23.setOpaque(true);
        jPanel1.add(a23);
        a23.setBounds(640, 70, 110, 28);

        jSalir.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jSalir.setForeground(new java.awt.Color(240, 240, 240));
        jSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/45.png"))); // NOI18N
        jSalir.setText("<");
        jSalir.setBorder(null);
        jSalir.setBorderPainted(false);
        jSalir.setContentAreaFilled(false);
        jSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jSalir.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/35.png"))); // NOI18N
        jSalir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/O_O/40.png"))); // NOI18N
        jSalir.setVerifyInputWhenFocusTarget(false);
        jSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSalirActionPerformed(evt);
            }
        });
        jPanel1.add(jSalir);
        jSalir.setBounds(20, 20, 31, 31);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondos/foptica.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 950, 460);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 950, 460);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
 AudioClip sonido;
        sonido= java.applet.Applet.newAudioClip(getClass().getResource("/audio/mirror.wav"));
        sonido.play();        // TODO add your handling code here:
        a1.setVisible(true);
        a2.setVisible(false);
        a3.setVisible(false);
        a4.setVisible(false);
        a5.setVisible(false);
        a6.setVisible(false);
        a7.setVisible(false);
        a8.setVisible(false);
        a9.setVisible(false);
        a10.setVisible(false);
        a11.setVisible(false);
        a111.setVisible(false);
        a12.setVisible(false);
        a13.setVisible(false);
        a14.setVisible(false);
        a15.setVisible(false);
        a16.setVisible(false);
        a17.setVisible(false);
        a18.setVisible(false);
        a19.setVisible(false);
        a20.setVisible(false);
        a21.setVisible(false);
        a22.setVisible(false);
        a23.setVisible(false);
        a24.setVisible(false);
        a25.setVisible(false);
       
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
 AudioClip sonido;
        sonido= java.applet.Applet.newAudioClip(getClass().getResource("/audio/ilumination.wav"));
        sonido.play();        // TODO add your handling code here:
        a1.setVisible(false);
        a2.setVisible(false);
        a3.setVisible(false);
        a4.setVisible(true);
        a5.setVisible(false);
        a6.setVisible(false);
        a7.setVisible(false);
        a8.setVisible(false);
        a9.setVisible(false);
        a10.setVisible(false);
        a11.setVisible(false);
        a111.setVisible(false);
        a12.setVisible(false);
        a13.setVisible(false);
        a14.setVisible(false);
        a15.setVisible(false);
        a16.setVisible(false);
        a17.setVisible(false);
        a18.setVisible(false);
        a19.setVisible(false);
        a20.setVisible(false);
        a21.setVisible(false);
        a22.setVisible(false);
        a23.setVisible(false);
        a24.setVisible(false);
        a25.setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
 AudioClip sonido;
        sonido= java.applet.Applet.newAudioClip(getClass().getResource("/audio/shelves.wav"));
        sonido.play();        // TODO add your handling code here:
        a1.setVisible(false);
        a2.setVisible(false);
        a3.setVisible(true);
        a4.setVisible(false);
        a5.setVisible(false);
        a6.setVisible(false);
        a7.setVisible(false);
        a8.setVisible(false);
        a9.setVisible(false);
        a10.setVisible(false);
        a11.setVisible(false);
        a111.setVisible(false);
        a12.setVisible(false);
        a13.setVisible(false);
        a14.setVisible(false);
        a15.setVisible(false);
        a16.setVisible(false);
        a17.setVisible(false);
        a18.setVisible(false);
        a19.setVisible(false);
        a20.setVisible(false);
        a21.setVisible(false);
        a22.setVisible(false);
        a23.setVisible(false);
        a24.setVisible(false);
        a25.setVisible(false);
       
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
 AudioClip sonido;
        sonido= java.applet.Applet.newAudioClip(getClass().getResource("/audio/photo.wav"));
        sonido.play();        // TODO add your handling code here:
        a1.setVisible(false);
        a2.setVisible(false);
        a3.setVisible(false);
        a4.setVisible(false);
        a5.setVisible(true);
        a6.setVisible(false);
        a7.setVisible(false);
        a8.setVisible(false);
        a9.setVisible(false);
        a10.setVisible(false);
        a11.setVisible(false);
        a111.setVisible(false);
        a12.setVisible(false);
        a13.setVisible(false);
        a14.setVisible(false);
        a15.setVisible(false);
        a16.setVisible(false);
        a17.setVisible(false);
        a18.setVisible(false);
        a19.setVisible(false);
        a20.setVisible(false);
        a21.setVisible(false);
        a22.setVisible(false);
        a23.setVisible(false);
        a24.setVisible(false);
        a25.setVisible(false);
       
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
 AudioClip sonido;
        sonido= java.applet.Applet.newAudioClip(getClass().getResource("/audio/zoom lenses.wav"));
        sonido.play();        // TODO add your handling code here:
        a1.setVisible(false);
        a2.setVisible(false);
        a3.setVisible(false);
        a4.setVisible(false);
        a5.setVisible(false);
        a6.setVisible(false);
        a7.setVisible(true);
        a8.setVisible(false);
        a9.setVisible(false);
        a10.setVisible(false);
        a11.setVisible(false);
        a111.setVisible(false);
        a12.setVisible(false);
        a13.setVisible(false);
        a14.setVisible(false);
        a15.setVisible(false);
        a16.setVisible(false);
        a17.setVisible(false);
        a18.setVisible(false);
        a19.setVisible(false);
        a20.setVisible(false);
        a21.setVisible(false);
        a22.setVisible(false);
        a23.setVisible(false);
        a24.setVisible(false);
        a25.setVisible(false);
       
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
 AudioClip sonido;
        sonido= java.applet.Applet.newAudioClip(getClass().getResource("/audio/ophthalmologist.wav"));
        sonido.play();        // TODO add your handling code here:
        a1.setVisible(false);
        a2.setVisible(false);
        a3.setVisible(false);
        a4.setVisible(false);
        a5.setVisible(false);
        a6.setVisible(false);
        a7.setVisible(false);
        a8.setVisible(true);
        a9.setVisible(false);
        a10.setVisible(false);
        a11.setVisible(false);
        a111.setVisible(false);
        a12.setVisible(false);
        a13.setVisible(false);
        a14.setVisible(false);
        a15.setVisible(false);
        a16.setVisible(false);
        a17.setVisible(false);
        a18.setVisible(false);
        a19.setVisible(false);
        a20.setVisible(false);
        a21.setVisible(false);
        a22.setVisible(false);
        a23.setVisible(false);
        a24.setVisible(false);
        a25.setVisible(false);
       
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
 AudioClip sonido;
        sonido= java.applet.Applet.newAudioClip(getClass().getResource("/audio/patient.wav"));
        sonido.play();        // TODO add your handling code here:
        a1.setVisible(false);
        a2.setVisible(false);
        a3.setVisible(false);
        a4.setVisible(false);
        a5.setVisible(false);
        a6.setVisible(false);
        a7.setVisible(false);
        a8.setVisible(false);
        a9.setVisible(true);
        a10.setVisible(false);
        a11.setVisible(false);
        a111.setVisible(false);
        a12.setVisible(false);
        a13.setVisible(false);
        a14.setVisible(false);
        a15.setVisible(false);
        a16.setVisible(false);
        a17.setVisible(false);
        a18.setVisible(false);
        a19.setVisible(false);
        a20.setVisible(false);
        a21.setVisible(false);
        a22.setVisible(false);
        a23.setVisible(false);
        a24.setVisible(false);
        a25.setVisible(false);
      
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
 AudioClip sonido;
        sonido= java.applet.Applet.newAudioClip(getClass().getResource("/audio/nurse.wav"));
        sonido.play();        // TODO add your handling code here:
        a1.setVisible(false);
        a2.setVisible(false);
        a3.setVisible(false);
        a4.setVisible(false);
        a5.setVisible(false);
        a6.setVisible(false);
        a7.setVisible(false);
        a8.setVisible(false);
        a9.setVisible(false);
        a10.setVisible(false);
        a11.setVisible(false);
        a111.setVisible(false);
        a12.setVisible(false);
        a13.setVisible(false);
        a14.setVisible(false);
        a15.setVisible(true);
        a16.setVisible(false);
        a17.setVisible(false);
        a18.setVisible(false);
        a19.setVisible(false);
        a20.setVisible(false);
        a21.setVisible(false);
        a22.setVisible(false);
        a23.setVisible(false);
        a24.setVisible(false);
        a25.setVisible(false);
       
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
 AudioClip sonido;
        sonido= java.applet.Applet.newAudioClip(getClass().getResource("/audio/ophthalmological furniture.wav"));
        sonido.play();        // TODO add your handling code here:
        a1.setVisible(false);
        a2.setVisible(false);
        a3.setVisible(false);
        a4.setVisible(false);
        a5.setVisible(false);
        a6.setVisible(false);
        a7.setVisible(false);
        a8.setVisible(false);
        a9.setVisible(false);
        a10.setVisible(false);
        a11.setVisible(true);
        a111.setVisible(true);
        a12.setVisible(false);
        a13.setVisible(false);
        a14.setVisible(false);
        a15.setVisible(false);
        a16.setVisible(false);
        a17.setVisible(false);
        a18.setVisible(false);
        a19.setVisible(false);
        a20.setVisible(false);
        a21.setVisible(false);
        a22.setVisible(false);
        a23.setVisible(false);
        a24.setVisible(false);
        a25.setVisible(false);
     
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
 AudioClip sonido;
        sonido= java.applet.Applet.newAudioClip(getClass().getResource("/audio/optometric chart.wav"));
        sonido.play();        // TODO add your handling code here:
        a1.setVisible(false);
        a2.setVisible(false);
        a3.setVisible(false);
        a4.setVisible(false);
        a5.setVisible(false);
        a6.setVisible(false);
        a7.setVisible(false);
        a8.setVisible(false);
        a9.setVisible(false);
        a10.setVisible(false);
        a11.setVisible(false);
        a111.setVisible(false);
        a12.setVisible(true);
        a13.setVisible(false);
        a14.setVisible(false);
        a15.setVisible(false);
        a16.setVisible(false);
        a17.setVisible(false);
        a18.setVisible(false);
        a19.setVisible(false);
        a20.setVisible(false);
        a21.setVisible(false);
        a22.setVisible(false);
        a23.setVisible(false);
        a24.setVisible(false);
        a25.setVisible(false);
        
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
 AudioClip sonido;
        sonido= java.applet.Applet.newAudioClip(getClass().getResource("/audio/clock.wav"));
        sonido.play();        // TODO add your handling code here:
        a1.setVisible(false);
        a2.setVisible(false);
        a3.setVisible(false);
        a4.setVisible(false);
        a5.setVisible(false);
        a6.setVisible(false);
        a7.setVisible(false);
        a8.setVisible(false);
        a9.setVisible(false);
        a10.setVisible(false);
        a11.setVisible(false);
        a111.setVisible(false);
        a12.setVisible(false);
        a13.setVisible(true);
        a14.setVisible(false);
        a15.setVisible(false);
        a16.setVisible(false);
        a17.setVisible(false);
        a18.setVisible(false);
        a19.setVisible(false);
        a20.setVisible(false);
        a21.setVisible(false);
        a22.setVisible(false);
        a23.setVisible(false);
        a24.setVisible(false);
        a25.setVisible(false);
      
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
 AudioClip sonido;
        sonido= java.applet.Applet.newAudioClip(getClass().getResource("/audio/notes.wav"));
        sonido.play();        // TODO add your handling code here:
        a1.setVisible(false);
        a2.setVisible(false);
        a3.setVisible(false);
        a4.setVisible(false);
        a5.setVisible(false);
        a6.setVisible(false);
        a7.setVisible(false);
        a8.setVisible(false);
        a9.setVisible(false);
        a10.setVisible(false);
        a11.setVisible(false);
        a111.setVisible(false);
        a12.setVisible(false);
        a13.setVisible(false);
        a14.setVisible(true);
        a15.setVisible(false);
        a16.setVisible(false);
        a17.setVisible(false);
        a18.setVisible(false);
        a19.setVisible(false);
        a20.setVisible(false);
        a21.setVisible(false);
        a22.setVisible(false);
        a23.setVisible(false);
        a24.setVisible(false);
        a25.setVisible(false);
        
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
 AudioClip sonido;
        sonido= java.applet.Applet.newAudioClip(getClass().getResource("/audio/computer.wav"));
        sonido.play();        // TODO add your handling code here:
        a1.setVisible(false);
        a2.setVisible(false);
        a3.setVisible(false);
        a4.setVisible(false);
        a5.setVisible(false);
        a6.setVisible(false);
        a7.setVisible(false);
        a8.setVisible(false);
        a9.setVisible(false);
        a10.setVisible(false);
        a11.setVisible(false);
        a111.setVisible(false);
        a12.setVisible(false);
        a13.setVisible(false);
        a14.setVisible(false);
        a15.setVisible(false);
        a16.setVisible(true);
        a17.setVisible(false);
        a18.setVisible(false);
        a19.setVisible(false);
        a20.setVisible(false);
        a21.setVisible(false);
        a22.setVisible(false);
        a23.setVisible(false);
        a24.setVisible(false);
        a25.setVisible(false);
       
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
 AudioClip sonido;
        sonido= java.applet.Applet.newAudioClip(getClass().getResource("/audio/glasses.wav"));
        sonido.play();        // TODO add your handling code here:
        a1.setVisible(false);
        a2.setVisible(true);
        a3.setVisible(false);
        a4.setVisible(false);
        a5.setVisible(false);
        a6.setVisible(false);
        a7.setVisible(false);
        a8.setVisible(false);
        a9.setVisible(false);
        a10.setVisible(false);
        a11.setVisible(false);
        a111.setVisible(false);
        a12.setVisible(false);
        a13.setVisible(false);
        a14.setVisible(false);
        a15.setVisible(false);
        a16.setVisible(false);
        a17.setVisible(false);
        a18.setVisible(false);
        a19.setVisible(false);
        a20.setVisible(false);
        a21.setVisible(false);
        a22.setVisible(false);
        a23.setVisible(false);
        a24.setVisible(false);
        a25.setVisible(false);
     
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
 AudioClip sonido;
        sonido= java.applet.Applet.newAudioClip(getClass().getResource("/audio/table.wav"));
        sonido.play();        // TODO add your handling code here:
        a1.setVisible(false);
        a2.setVisible(false);
        a3.setVisible(false);
        a4.setVisible(false);
        a5.setVisible(false);
        a6.setVisible(false);
        a7.setVisible(false);
        a8.setVisible(false);
        a9.setVisible(false);
        a10.setVisible(false);
        a11.setVisible(false);
        a111.setVisible(false);
        a12.setVisible(false);
        a13.setVisible(false);
        a14.setVisible(false);
        a15.setVisible(false);
        a16.setVisible(false);
        a17.setVisible(false);
        a18.setVisible(false);
        a19.setVisible(true);
        a20.setVisible(false);
        a21.setVisible(false);
        a22.setVisible(false);
        a23.setVisible(false);
        a24.setVisible(false);
        a25.setVisible(false);
       
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
 AudioClip sonido;
        sonido= java.applet.Applet.newAudioClip(getClass().getResource("/audio/lamp.wav"));
        sonido.play();        // TODO add your handling code here:
        a1.setVisible(false);
        a2.setVisible(false);
        a3.setVisible(false);
        a4.setVisible(false);
        a5.setVisible(false);
        a6.setVisible(true);
        a7.setVisible(false);
        a8.setVisible(false);
        a9.setVisible(false);
        a10.setVisible(false);
        a11.setVisible(false);
        a111.setVisible(false);
        a12.setVisible(false);
        a13.setVisible(false);
        a14.setVisible(false);
        a15.setVisible(false);
        a16.setVisible(false);
        a17.setVisible(false);
        a18.setVisible(false);
        a19.setVisible(false);
        a20.setVisible(false);
        a21.setVisible(false);
        a22.setVisible(false);
        a23.setVisible(false);
        a24.setVisible(false);
        a25.setVisible(false);
        
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
 AudioClip sonido;
        sonido= java.applet.Applet.newAudioClip(getClass().getResource("/audio/SEAT.wav"));
        sonido.play();        // TODO add your handling code here:
        a1.setVisible(false);
        a2.setVisible(false);
        a3.setVisible(false);
        a4.setVisible(false);
        a5.setVisible(false);
        a6.setVisible(false);
        a7.setVisible(false);
        a8.setVisible(false);
        a9.setVisible(false);
        a10.setVisible(true);
        a11.setVisible(false);
        a111.setVisible(false);
        a12.setVisible(false);
        a13.setVisible(false);
        a14.setVisible(false);
        a15.setVisible(false);
        a16.setVisible(false);
        a17.setVisible(false);
        a18.setVisible(false);
        a19.setVisible(false);
        a20.setVisible(false);
        a21.setVisible(false);
        a22.setVisible(false);
        a23.setVisible(false);
        a24.setVisible(false);
        a25.setVisible(false);
       
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
 AudioClip sonido;
        sonido= java.applet.Applet.newAudioClip(getClass().getResource("/audio/markers.wav"));
        sonido.play();        // TODO add your handling code here:
        a1.setVisible(false);
        a2.setVisible(false);
        a3.setVisible(false);
        a4.setVisible(false);
        a5.setVisible(false);
        a6.setVisible(false);
        a7.setVisible(false);
        a8.setVisible(false);
        a9.setVisible(false);
        a10.setVisible(false);
        a11.setVisible(false);
        a111.setVisible(false);
        a12.setVisible(false);
        a13.setVisible(false);
        a14.setVisible(false);
        a15.setVisible(false);
        a16.setVisible(false);
        a17.setVisible(false);
        a18.setVisible(false);
        a19.setVisible(false);
        a20.setVisible(true);
        a21.setVisible(false);
        a22.setVisible(false);
        a23.setVisible(false);
        a24.setVisible(false);
        a25.setVisible(false);
        
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
 AudioClip sonido;
        sonido= java.applet.Applet.newAudioClip(getClass().getResource("/audio/box.wav"));
        sonido.play();        // TODO add your handling code here:
        a1.setVisible(false);
        a2.setVisible(false);
        a3.setVisible(false);
        a4.setVisible(false);
        a5.setVisible(false);
        a6.setVisible(false);
        a7.setVisible(false);
        a8.setVisible(false);
        a9.setVisible(false);
        a10.setVisible(false);
        a11.setVisible(false);
        a111.setVisible(false);
        a12.setVisible(false);
        a13.setVisible(false);
        a14.setVisible(false);
        a15.setVisible(false);
        a16.setVisible(false);
        a17.setVisible(false);
        a18.setVisible(false);
        a19.setVisible(false);
        a20.setVisible(false);
        a21.setVisible(false);
        a22.setVisible(true);
        a23.setVisible(false);
        a24.setVisible(false);
        a25.setVisible(false);
       
        
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
 AudioClip sonido;
        sonido= java.applet.Applet.newAudioClip(getClass().getResource("/audio/PENCILS.wav"));
        sonido.play();        // TODO add your handling code here:
        a1.setVisible(false);
        a2.setVisible(false);
        a3.setVisible(false);
        a4.setVisible(false);
        a5.setVisible(false);
        a6.setVisible(false);
        a7.setVisible(false);
        a8.setVisible(false);
        a9.setVisible(false);
        a10.setVisible(false);
        a11.setVisible(false);
        a111.setVisible(false);
        a12.setVisible(false);
        a13.setVisible(false);
        a14.setVisible(false);
        a15.setVisible(false);
        a16.setVisible(false);
        a17.setVisible(false);
        a18.setVisible(false);
        a19.setVisible(false);
        a20.setVisible(false);
        a21.setVisible(true);
        a22.setVisible(false);
        a23.setVisible(false);
        a24.setVisible(false);
        a25.setVisible(false);
        
        
    }//GEN-LAST:event_jButton24ActionPerformed

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
 AudioClip sonido;
        sonido= java.applet.Applet.newAudioClip(getClass().getResource("/audio/screw.wav"));
        sonido.play();        // TODO add your handling code here:
        a1.setVisible(false);
        a2.setVisible(false);
        a3.setVisible(false);
        a4.setVisible(false);
        a5.setVisible(false);
        a6.setVisible(false);
        a7.setVisible(false);
        a8.setVisible(false);
        a9.setVisible(false);
        a10.setVisible(false);
        a11.setVisible(false);
        a111.setVisible(false);
        a12.setVisible(false);
        a13.setVisible(false);
        a14.setVisible(false);
        a15.setVisible(false);
        a16.setVisible(false);
        a17.setVisible(false);
        a18.setVisible(false);
        a19.setVisible(false);
        a20.setVisible(false);
        a21.setVisible(false);
        a22.setVisible(false);
        a23.setVisible(true);
        a24.setVisible(false);
        a25.setVisible(false);
      
        
    }//GEN-LAST:event_jButton25ActionPerformed

    private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton26ActionPerformed
 AudioClip sonido;
        sonido= java.applet.Applet.newAudioClip(getClass().getResource("/audio/drawer.wav"));
        sonido.play();        // TODO add your handling code here:
        a1.setVisible(false);
        a2.setVisible(false);
        a3.setVisible(false);
        a4.setVisible(false);
        a5.setVisible(false);
        a6.setVisible(false);
        a7.setVisible(false);
        a8.setVisible(false);
        a9.setVisible(false);
        a10.setVisible(false);
        a11.setVisible(false);
        a111.setVisible(false);
        a12.setVisible(false);
        a13.setVisible(false);
        a14.setVisible(false);
        a15.setVisible(false);
        a16.setVisible(false);
        a17.setVisible(false);
        a18.setVisible(false);
        a19.setVisible(false);
        a20.setVisible(false);
        a21.setVisible(false);
        a22.setVisible(false);
        a23.setVisible(false);
        a24.setVisible(true);
        a25.setVisible(false);
        
    }//GEN-LAST:event_jButton26ActionPerformed

    private void jButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton27ActionPerformed
 AudioClip sonido;
        sonido= java.applet.Applet.newAudioClip(getClass().getResource("/audio/eye.wav"));
        sonido.play();        // TODO add your handling code here:
        a1.setVisible(false);
        a2.setVisible(false);
        a3.setVisible(false);
        a4.setVisible(false);
        a5.setVisible(false);
        a6.setVisible(false);
        a7.setVisible(false);
        a8.setVisible(false);
        a9.setVisible(false);
        a10.setVisible(false);
        a11.setVisible(false);
        a111.setVisible(false);
        a12.setVisible(false);
        a13.setVisible(false);
        a14.setVisible(false);
        a15.setVisible(false);
        a16.setVisible(false);
        a17.setVisible(false);
        a18.setVisible(false);
        a19.setVisible(false);
        a20.setVisible(false);
        a21.setVisible(false);
        a22.setVisible(false);
        a23.setVisible(false);
        a24.setVisible(false);
        a25.setVisible(true);
       
    }//GEN-LAST:event_jButton27ActionPerformed

    private void jButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton28ActionPerformed
 AudioClip sonido;
        sonido= java.applet.Applet.newAudioClip(getClass().getResource("/audio/air conditioner.wav"));
        sonido.play();        // TODO add your handling code here:
        a1.setVisible(false);
        a2.setVisible(false);
        a3.setVisible(false);
        a4.setVisible(false);
        a5.setVisible(false);
        a6.setVisible(false);
        a7.setVisible(false);
        a8.setVisible(false);
        a9.setVisible(false);
        a10.setVisible(false);
        a11.setVisible(false);
        a111.setVisible(false);
        a12.setVisible(false);
        a13.setVisible(false);
        a14.setVisible(false);
        a15.setVisible(false);
        a16.setVisible(false);
        a17.setVisible(false);
        a18.setVisible(true);
        a19.setVisible(false);
        a20.setVisible(false);
        a21.setVisible(false);
        a22.setVisible(false);
        a23.setVisible(false);
        a24.setVisible(false);
        a25.setVisible(false);
        
    }//GEN-LAST:event_jButton28ActionPerformed

    private void jButton29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton29ActionPerformed
 AudioClip sonido;
        sonido= java.applet.Applet.newAudioClip(getClass().getResource("/audio/chair.wav"));
        sonido.play();        // TODO add your handling code here:
        a1.setVisible(false);
        a2.setVisible(false);
        a3.setVisible(false);
        a4.setVisible(false);
        a5.setVisible(false);
        a6.setVisible(false);
        a7.setVisible(false);
        a8.setVisible(false);
        a9.setVisible(false);
        a10.setVisible(false);
        a11.setVisible(false);
        a111.setVisible(false);
        a12.setVisible(false);
        a13.setVisible(false);
        a14.setVisible(false);
        a15.setVisible(false);
        a16.setVisible(false);
        a17.setVisible(true);
        a18.setVisible(false);
        a19.setVisible(false);
        a20.setVisible(false);
        a21.setVisible(false);
        a22.setVisible(false);
        a23.setVisible(false);
        a24.setVisible(false);
        a25.setVisible(false);
       
        
    }//GEN-LAST:event_jButton29ActionPerformed

    private void jSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSalirActionPerformed
        new Menu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Optica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Optica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Optica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Optica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Optica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel a1;
    private javax.swing.JLabel a10;
    private javax.swing.JLabel a11;
    private javax.swing.JLabel a111;
    private javax.swing.JLabel a12;
    private javax.swing.JLabel a13;
    private javax.swing.JLabel a14;
    private javax.swing.JLabel a15;
    private javax.swing.JLabel a16;
    private javax.swing.JLabel a17;
    private javax.swing.JLabel a18;
    private javax.swing.JLabel a19;
    private javax.swing.JLabel a2;
    private javax.swing.JLabel a20;
    private javax.swing.JLabel a21;
    private javax.swing.JLabel a22;
    private javax.swing.JLabel a23;
    private javax.swing.JLabel a24;
    private javax.swing.JLabel a25;
    private javax.swing.JLabel a3;
    private javax.swing.JLabel a4;
    private javax.swing.JLabel a5;
    private javax.swing.JLabel a6;
    private javax.swing.JLabel a7;
    private javax.swing.JLabel a8;
    private javax.swing.JLabel a9;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jSalir;
    // End of variables declaration//GEN-END:variables
}
