/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Cuestionarios;




import Modulos.Inicio;
import com.sun.awt.AWTUtilities;
import javax.swing.JOptionPane;


/**
 *
 * @author USUARIO
 */
public class Menu_Test extends javax.swing.JFrame {

    int x;
    int y;
            
    public Menu_Test() {
        initComponents();
        this.setLocationRelativeTo(null);
        AWTUtilities.setWindowOpaque(this, false);
        bSiguiente.setEnabled(false);
        op_test.add(checkBox1);
        op_test.add(checkBox2);
    }        
/*    
0  Baby Shop
1  Bank
2  Beauty
3  Book Shop
4  Cafetery
5  Candy Shop
6  Casino
7  Cinema
8  Clothes Store
9  Computer Store
10 Electronic
11 Fast Food
12 Jewrly
13 Optic
14 Parking lot
15 Pets
16 Restaurant
17 Sports
18 Telephone
19 Toy Shop
20 Videogame Shop
21 WC
*/

    int c;
        
    F_Cuestionario FC = new F_Cuestionario();
    I_Cuestionario IC = new I_Cuestionario();
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        op_test = new javax.swing.ButtonGroup();
        jLabel3 = new javax.swing.JLabel();
        bMinimizar = new javax.swing.JButton();
        bSalir = new javax.swing.JButton();
        bSiguiente = new javax.swing.JButton();
        lBarra = new javax.swing.JLabel();
        checkBox1 = new javax.swing.JCheckBox();
        tf1 = new javax.swing.JTextField();
        checkBox2 = new javax.swing.JCheckBox();
        cb_2 = new javax.swing.JComboBox<>();
        cb_1 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Test");
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(650, 350));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 40, 110, 30);

        bMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cuestionarios/Botones/Minimizar/20.png"))); // NOI18N
        bMinimizar.setBorder(null);
        bMinimizar.setBorderPainted(false);
        bMinimizar.setContentAreaFilled(false);
        bMinimizar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Cuestionarios/Botones/Minimizar/10.png"))); // NOI18N
        bMinimizar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Cuestionarios/Botones/Minimizar/15.png"))); // NOI18N
        bMinimizar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Cuestionarios/Botones/Minimizar/20.png"))); // NOI18N
        bMinimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMinimizarActionPerformed(evt);
            }
        });
        getContentPane().add(bMinimizar);
        bMinimizar.setBounds(595, 5, 20, 21);

        bSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cuestionarios/Botones/Salir/20.png"))); // NOI18N
        bSalir.setBorder(null);
        bSalir.setBorderPainted(false);
        bSalir.setContentAreaFilled(false);
        bSalir.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Cuestionarios/Botones/Salir/10.png"))); // NOI18N
        bSalir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Cuestionarios/Botones/Salir/15.png"))); // NOI18N
        bSalir.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Cuestionarios/Botones/Salir/10.png"))); // NOI18N
        bSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalirActionPerformed(evt);
            }
        });
        getContentPane().add(bSalir);
        bSalir.setBounds(620, 5, 20, 21);

        bSiguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cuestionarios/Botones/Siguiente/Next150.png"))); // NOI18N
        bSiguiente.setBorderPainted(false);
        bSiguiente.setContentAreaFilled(false);
        bSiguiente.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Cuestionarios/Botones/Siguiente/Next130.png"))); // NOI18N
        bSiguiente.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Cuestionarios/Botones/Siguiente/Next140.png"))); // NOI18N
        bSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSiguienteActionPerformed(evt);
            }
        });
        getContentPane().add(bSiguiente);
        bSiguiente.setBounds(250, 290, 150, 45);

        lBarra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cuestionarios/Barra.jpg"))); // NOI18N
        lBarra.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lBarra.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lBarraMouseDragged(evt);
            }
        });
        lBarra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lBarraMousePressed(evt);
            }
        });
        getContentPane().add(lBarra);
        lBarra.setBounds(0, 0, 650, 30);

        checkBox1.setOpaque(false);
        checkBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(checkBox1);
        checkBox1.setBounds(50, 161, 190, 30);

        tf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf1ActionPerformed(evt);
            }
        });
        getContentPane().add(tf1);
        tf1.setBounds(267, 103, 160, 30);

        checkBox2.setOpaque(false);
        checkBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(checkBox2);
        checkBox2.setBounds(420, 161, 150, 30);

        cb_2.setBackground(new java.awt.Color(102, 102, 255));
        cb_2.setFont(new java.awt.Font("Caviar Dreams", 1, 24)); // NOI18N
        cb_2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2.0  Baby Shop", "2.1  Bank", "2.2  Beauty", "2.3  Book Shop", "2.4  Cafetery", "2.5  Candy Shop", "2.6  Casino", "2.7  Cinema", "2.8  Clothes Store", "2.9  Computer Store", "2.10 Electronic", "2.11 Fast Food", "2.12 Jewrly", "2.13 Optic", "2.14 Parking lot", "2.15 Pets", "2.16 Restaurant", "2.17 Sports", "2.18 Telephone", "2.19 Toy Shop", "2.20 Videogame Shop", "2.21 WC" }));
        cb_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_2ActionPerformed(evt);
            }
        });
        getContentPane().add(cb_2);
        cb_2.setBounds(340, 203, 290, 50);

        cb_1.setBackground(new java.awt.Color(102, 102, 255));
        cb_1.setFont(new java.awt.Font("Caviar Dreams", 1, 24)); // NOI18N
        cb_1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1.0  Baby Shop", "1.1  Bank", "1.2  Beauty", "1.3  Book Shop", "1.4  Cafetery  ", "1.5  Candy Shop", "1.6  Casino ", "1.7  Cinema ", "1.8  Clothes Store ", "1.9  Computer Store ", "1.10 Electronic", "1.11 Fast Food", "1.12 Jewrly", "1.13 Optic", "1.14 Parking lot ", "1.15 Pets", "1.16 Restaurant", "1.17 Sports ", "1.18 Telephone", "1.19 Toy Shop ", "1.20 Videogame Shop", "1.21 WC" }));
        getContentPane().add(cb_1);
        cb_1.setBounds(20, 203, 290, 50);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cuestionarios/MenuPrincipal.jpg"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 650, 350);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSiguienteActionPerformed
    
    if(tf1.getText().isEmpty()){
        JOptionPane.showMessageDialog(null,"Enter your ID");
    }else{
        this.dispose();
        FC.nom = tf1.getText();
        IC.nom = tf1.getText();
        if(checkBox1.isSelected()){
            FC.eje1 = cb_1.getSelectedIndex();        
            FC.setVisible(true);
        }
        if(checkBox2.isSelected()){
            IC.eje2 = cb_2.getSelectedIndex();        
            IC.setVisible(true);
        }
        
    }
    
//   new Menu_Test().setVisible(true);
        
    }//GEN-LAST:event_bSiguienteActionPerformed

    private void tf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf1ActionPerformed

    private void checkBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBox1ActionPerformed
        // TODO add your handling code here:
        cb_1.setEnabled(true);
        cb_2.setEnabled(false);
        bSiguiente.setEnabled(true);
    }//GEN-LAST:event_checkBox1ActionPerformed

    private void checkBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBox2ActionPerformed
        // TODO add your handling code here:
        cb_1.setEnabled(false);
        cb_2.setEnabled(true);
        bSiguiente.setEnabled(true);
    }//GEN-LAST:event_checkBox2ActionPerformed

    private void cb_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_2ActionPerformed

    private void bSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalirActionPerformed
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_bSalirActionPerformed

    private void lBarraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lBarraMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_lBarraMousePressed

    private void lBarraMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lBarraMouseDragged
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_lBarraMouseDragged

    private void bMinimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMinimizarActionPerformed
        this.setExtendedState(ICONIFIED);
        this.setExtendedState(1);
    }//GEN-LAST:event_bMinimizarActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
                new Inicio().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_Test().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bMinimizar;
    private javax.swing.JButton bSalir;
    private javax.swing.JButton bSiguiente;
    private javax.swing.JComboBox<String> cb_1;
    private javax.swing.JComboBox<String> cb_2;
    private javax.swing.JCheckBox checkBox1;
    private javax.swing.JCheckBox checkBox2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lBarra;
    private javax.swing.ButtonGroup op_test;
    private javax.swing.JTextField tf1;
    // End of variables declaration//GEN-END:variables
}
